### ISSUE TITLE
CMake and how to apply options file to all proto files (i.e. globally)

### ISSUE THREAD

**Issue by atelszewski** [nanopb/nanopb#1019]
Hello,

I'm looking for a way to apply single options file to all `.proto` files.
I'm using CMake and `NANOPB_GENERATE_CPP()`.

I found that it's possible to apply options _per_ `.proto` file, if the options file name corresponds to the `.proto` file name.

But how can I have a single _options_ file be applied for all `.proto` files?

Thanks for your help! :-)

--
Best regards,
Andrzej Telszewski

**Comment by PetteriAimonen** [comment]
I think something like this would work:

    list(APPEND NANOPB_OPTIONS "--options-file=myfile.options")

The full list of generator command line options can be had with `nanopb_generator.py --help`.

**Comment by atelszewski** [comment]
That did the trick, thank you!

(Apparently I already tried this solution before asking here, but failed due to some hiccups.)

Thanks!
