### ISSUE TITLE
Null pointer dereference in buf_write

### ISSUE THREAD

**Issue by canton7** [nanopb/nanopb#1030]
This one popped up while running cppcheck on our codebase, and it seems to be genuine:

```
pb_encode.c:58:18: error: Null pointer dereference: buf [ctunullpointer]
    memcpy(dest, buf, count * sizeof(pb_byte_t));
                 ^
pb_encode.c:178:28: note: Calling function pb_write, 2nd argument is null
            return pb_write(stream, NULL, size); /* Just sizing.. */
                           ^
pb_encode.c:95:14: note: Calling function buf_write, 2nd argument is null
        if (!buf_write(stream, buf, count))
             ^
pb_encode.c:58:18: note: Dereferencing argument buf that is null
    memcpy(dest, buf, count * sizeof(pb_byte_t));
```

* `encode_array` calls `pb_write`, passing `NULL` as the `buf` parameter
* If `PB_BUFFER_ONLY` is defined, `pb_write` calls `buf_write`, passing that same NULL `buf`
* `buf_write` passes that NULL `buf` to `memcpy`

**Comment by PetteriAimonen** [comment]
The call at line 178:

        if (stream->callback == NULL)
            return pb_write(stream, NULL, size); /* Just sizing.. */

Precondition in `pb_write()` on line 86:

    if (count > 0 && stream->callback != NULL)

So it will not end in the `buf_write()`.

This logic is part of being able to calculate the size of a message without writing it out. It's needed because protobuf requires prepending the size of packed arrays before the actual array.

**Comment by canton7** [comment]
Aah yes right you are, I missed that thanks.
