### ISSUE TITLE
Options for bytes fields do not work

### ISSUE THREAD

**Issue by controlol** [nanopb/nanopb#1036]
When creating a message with a `bytes` field type the options are not applied in the generated header files. When using a options file to set the `max_count` and `fixed_count` the generated C type is still pb_callback_t. Changing the type to `repeated uint32` does work and the correct type is generated.

This is the compile command
```sh
python ./nanopb/generator/nanopb_generator.py -s long_names:false -L quote --proto-path=proto --options-path=proto/options --out=gen test.proto
```

This is the content of the options file (test.options)
```
TestMessage.data                 max_count:1024
TestMessage.data                 fixed_count:true
```

Content of the proto file (test.proto)
```proto
message TestMessage {
  bytes data = 1;
}
```

**Comment by PetteriAimonen** [comment]
`max_count` is for arrays, for bytes use `max_size`
