### ISSUE TITLE
*.option is searched in the execution directory instead of directory where the *.proto is

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nanopb/nanopb#116]
```
What steps will reproduce the problem?
1. create a make file project where the make file and the *.proto / *.option 
file is not in the same directory
e.g.
Build/Makefile
Config/alltypes.proto
Config/alltypes.option
2. command in the Makefile is:
$(NANOPB_SRC_GEN)/%.pb.c $(NANOPB_SRC_GEN)/%.pb.h: $(NANOPB_INPUT)/%.proto 
$(wildcard $(NANOPB_INPUT)/%.options)
    $(PROTOC) -I$(NANOPB_INPUT) --nanopb_out=$(NANOPB_SRC_GEN) $<
3. by calling the generator the *option file is ignored
4. change the command in the Makefile to:
$(NANOPB_SRC_GEN)/%.pb.c $(NANOPB_SRC_GEN)/%.pb.h: $(NANOPB_INPUT)/%.proto 
$(wildcard $(NANOPB_INPUT)/%.options)
    cd $(NANOPB_INPUT); $(PROTOC) -I$(NANOPB_INPUT) --nanopb_out=$(NANOPB_SRC_GEN) $<
the difference is the "cd $(NANOPB_INPUT); " before the generator call
5. the *.option file is used

What is the expected output? What do you see instead?
I expect as documented that the *option file is searched in the same directory 
as the *.proto file.

What version of the product are you using? On what operating system?
0.2.7 on Windows

Please provide any additional information below.


```

Original issue reported on code.google.com by `andreas....@gmail.com` on 30 Apr 2014 at 1:06

**Comment by PetteriAimonen** [comment]
Made pull request to protoc to get the necessary info passed on to nanopb's generator:
https://github.com/google/protobuf/pull/811

Once that goes through, this can be fixed - though it will only be fixed when used in combination with new protoc versions.

**Comment by mhaberler** [comment]
That one was important and bugged me as well, good move!

I take this will appear in protobuf3 only? or do they take 'backport' fixes for 2.6x?

**Comment by PetteriAimonen** [comment]
I've been using the newest git version of protoc on my system for a while. It still works for proto2 also, so no problem to use it with nanopb.

**Comment by mhaberler** [comment]
ah. that I was sort of afraid of jumping into the latest, will follow now;)

**Comment by kamathba** [comment]
+1, it looks tentatively accepted in protoc, is it scheduled for acceptance/merge?

**Comment by PetteriAimonen** [comment]
Protoc maintainers found a bit of uncovered ground in it, so it will require quite a bit of work still. I've been quite busy with other stuff, so haven't had time to rework the patch.

**Comment by jeremyherbert** [comment]
tripped on this one today, would be good to see if this can be fixed

**Comment by PetteriAimonen** [comment]
@jeremyherbert Would you feel like working on google/protobuf#811? It should be relatively simple addition, but without that protoc side change I don't think I can resolve this in nanopb.

**Comment by jeremyherbert** [comment]
I am unfortunately super busy with a current project, but I will try to come back to this when I am done with it :)

**Comment by PetteriAimonen** [comment]
Yeah, same for me :)

**Comment by lmapii** [comment]
strugglilng with the same issue here ..

**Comment by PetteriAimonen** [comment]
@lmapii In case it helps, specifying a separate include directory with -I to nanopb generator is a possible workaround. E.g.

<pre>
protoc -I my_proto_dir --nanopb_out=-Imy_proto_dir:my_output_dir msg.proto
</pre>

**Comment by lmapii** [comment]
that seems to do the trick too thanks. i have the .proto's in subfolders so basically i just have to pass all the directories specified for protoc to nanopb_out via -I too. seems to work so far.

```
T_PRO = $(foreach t, $(SUBDIRECTORY), ./$(t)/*.proto)
T_INC = $(foreach t, $(SUBDIRECTORY), -I./$(t))
PLUGIN = --plugin=protoc-gen-nanopb=$(NANOPB_PATH)/generator/protoc-gen-nanopb
> protoc $(T_INC) $(PLUGIN) --nanopb_out="$(T_INC)":./$(OUT_C) $(T_PRO)
```

**Comment by PetteriAimonen** [comment]
Yeah. The main problem in this issue is that protoc doesn't currently pass the `-I` arguments to plugins, so they have to be specified separately. And internally it seems that protoc `-I` syntax is more complex than what I assumed (it supports virtual directory mappings) which caused my initial patch to be rejected.

**Comment by lmapii** [comment]
ah i see. tried to use inline options instead but had issues with the generated code that wasn't C (counterpart is GO, ended up having circular references). 

anyhow, seeing that this issue is open since 2015 it would be nice if this workaround would be mentioned in the documentation ... it cost a lot of people a lot of time already i guess. otherwise nanopb is working really nicely

**Comment by PetteriAimonen** [comment]
@lmapii I agree, there is a note here now: https://jpa.kapsi.fi/nanopb/docs/reference.html#defining-the-options-in-a-options-file

**Comment by lmapii** [comment]
nice ! thanks !

**Comment by combsjy** [comment]
I don't think this issue should be closed as a result of #411.  Even the commit message says "if you use cmake".  I think this should be re-opened, or marked closed because it's _actually_ an upstream `protoc` defect.

**Comment by PetteriAimonen** [comment]
@combsjy Good point, I didn't actually mean to close this, GitHub did that automatically based on commit message.

**Comment by PetteriAimonen** [comment]
Finally there is some development on this.

Now with #462 `nanopb_generator.py` will automatically compile any `.proto` files given on command line, so it will have full knowledge of the path.

So, hopefully, running generation like: `python nanopb/generator/nanopb_generator.py my/complicated/../path/foo.proto` will work correctly, or at least can be made to work correctly.

But as a disclaimer, I haven't tested it very much yet.

**Comment by PetteriAimonen** [comment]
I'll close this old issue. There have been several small fixes to finding .options files over the years, but the underlying complexity still exists.

Now in 0.4.0, nanopb_generator.py accepts .proto files directly which makes it easier to find the related .options file.
