### ISSUE TITLE
Add option for defining message identifiers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nanopb/nanopb#151]
```
Describe the requested feature:
To properly decode protocol buffers messages, the correct message type has to 
be known. However, the .proto format provides no identifiers for messages. 
Using union messages / oneofs provides one way to do this, but is not very 
elegant when multiple files and large number of messages is involved.

Instead this could be offered as an option:

- Custom nanopb message-level option "uint32 msgid":

message msg1 {
   option (nanopb_msgopt).msgid = 1234;
   ..
}

- Compiler generates #define list of messages in each .pb.h file:

#define PB_MSG_1234 msg1
#define PB_MSG_5678 msg2

#define MYPROTOFILE1_MESSAGES PB_MSG(1234) PB_MSG(5678)

- The definition of PB_MSG_1234 etc. will give errors if multiple .h's with 
conflicting msgid's are included.

- The X-macros in the MYPROTOFILE1_MESSAGES can be used to e.g. construct list 
of messages like this:

typedef struct { uint32_t msgid; size_t size; pb_field_t *fields; } msginfo_t;

#define PB_MSG(id) {id, sizeof(PB_MSG_ ## id), PB_MSG_ ## id ## _fields},
msginfo_t msgs[] = {
  MYPROTOFILE1_MESSAGES
  MYPROTOFILE2_MESSAGES
  ..
};

- Only messages that have msgid option are included in the list. This way 
submessages will not be publicly exposed and do not need unique id's.


See here for prior discussion:
https://groups.google.com/forum/#!topic/nanopb/pZcrj-zbVEI




```

Original issue reported on code.google.com by `Petteri.Aimonen` on 21 Mar 2015 at 3:20

**Comment by barbiani** [comment]
Is this feature currently working as of version 0.4.5?

I am trying to compile this proto and the (nanopb_msgopt).msgid breaks it.

It seems that the request sent to the [python generator extension](https://github.com/rideskip/anchor/blob/master/sonar/protobuf/sonar_proto_gen.py) does not have the "parameter" field for this entry.

```
syntax = "proto2";

import "nanopb.proto";
import "sonar_extensions.proto";

message DeviceInfo {
    option (nanopb_msgopt).msgid = 0x264;
    option (sonar_msgopt).attr_ops = ATTR_OPS_R;

    enum HardwareRevision {
        UNKNOWN = 0;
        EVT = 1;
        DVT = 2;
        PVT = 3;
    }

    required HardwareRevision hardware_revision = 1;
    required string serial = 2 [(nanopb).max_size = 25];
}
```

**Comment by PetteriAimonen** [comment]
@barbiani The test case https://github.com/nanopb/nanopb/tree/master/tests/msgid is passing.
Try dumping the request from the custom Python extension to a file to see what is going on.

**Comment by barbiani** [comment]
Here it is.

Dumped the request with:

```
with open("request.log", 'w') as f:
                    print(request, file=f)

```

which does not seem to include a 'parameter' field anywhere.

[request.log](https://github.com/nanopb/nanopb/files/7800601/request.log)

**Comment by PetteriAimonen** [comment]
@barbiani The `parameter` field is only included by `protoc` when you actually give a generator parameter on the command line, e.g. `--myplugin-out=parameters:path`

But this does not seem like an issue in nanopb, but a problem with `sonar_proto_gen.py`.

**Comment by barbiani** [comment]
I can confirm that nanopb is working fine without the sonar extension.

The original sonar project documentation missed passing the parameter.

Thank you.
