### ISSUE TITLE
Ambiguous function all

### ISSUE THREAD

**Issue by lenonk** [nanopb/nanopb#158]
In utility.cc, @ line 305, isnan(value) in ambiguous when compiled with c++.  It should be std::isnan(value)

**Comment by PetteriAimonen** [comment]
Hmm.. I don't see a utility.cc or isnan() in the whole project. Can you give a link to what file you are talking about?

**Comment by PetteriAimonen** [comment]
I'm closing this as an invalid report as it does not make any sense to me. Maybe reported against a wrong project?
