### ISSUE TITLE
Support Any message type

### ISSUE THREAD

**Issue by vahid-sohrabloo** [nanopb/nanopb#163]
Is nanopb support Any message type?
https://developers.google.com/protocol-buffers/docs/proto3?hl=en#any

**Comment by PetteriAimonen** [comment]
No, there is no protobuf 3 support in nanopb so far.

**Comment by PetteriAimonen** [comment]
Hmm, looking at the google/protobuf/any.proto file, looks like it might work even without any special support. Like this:

    message MyMsg {
         Any details = 1 [(nanopb).max_size = 5];
    }

and:

    MyMsg msg;
    pb_decode(...., &msg);
    if (strcmp(msg.details.type_url, "http://my-id-url.com/foo.proto") == 0)
    {
           Foo foobar;
           pb_istream_t s = pb_istream_from_buffer(msg.details.value.bytes, msg.details.value.size);
           pb_decode(&s, Foo_fields, &foobar);
    }

**Comment by Jingzhe88** [comment]
Hi @PetteriAimonen, 

Could you point to an example to use any in the nanopb? I have searched around, but could not find any but this related issue. 

Thanks, 
James

**Comment by wuzhenda** [comment]
need encode  example too

**Comment by wuzhenda** [comment]
> Hmm, looking at the google/protobuf/any.proto file, looks like it might work even without any special support. Like this:
> 
> ```
> message MyMsg {
>      Any details = 1 [(nanopb).max_size = 5];
> }
> ```
> 
> and:
> 
> ```
> MyMsg msg;
> pb_decode(...., &msg);
> if (strcmp(msg.details.type_url, "http://my-id-url.com/foo.proto") == 0)
> {
>        Foo foobar;
>        pb_istream_t s = pb_istream_from_buffer(msg.details.value.bytes, msg.details.value.size);
>        pb_decode(&s, Foo_fields, &foobar);
> }
> ```

msg.details.type_url is a pb_callback_t type not string

**Comment by PetteriAimonen** [comment]
I've now added a test case / example on Any type usage.
