### ISSUE TITLE
Support Code Generator Plugin Insertion Points

### ISSUE THREAD

**Issue by tullisar** [nanopb/nanopb#178]
It would be useful for nanopb to have insertion points (as described in plugin.proto) in it's generated code, so that other code generator plugins could add additional target specific code where necessary. A couple useful locations that I think of:

Header files (.pb.h):
- Top of file scope (for perhaps inserting copyright or other header comments)
- Include scope (after includes that nanopb adds)
- Pre and post-type declarations (prior to all enum/structs nanopb creates)
- Message struct scope (within the scope of a struct created by nanopb, after the fields)
- Enum scope? (maybe for code that could appear before or after an enum declaration)

Source file (.pb.c)
- Include scope (after includes that nanopb adds)
- Pre and post-field descriptors (prior to the field descriptor definitions)

**Comment by PetteriAimonen** [comment]
I have now added insertion points at:
1. include directives
2. every message struct
3. end of file

I do not wish to fill the files with these without need, though. So more points can be added but will need a specific use case and a separate issue report.

**Comment by PetteriAimonen** [comment]
Feature released in nanopb-0.3.5.
