### ISSUE TITLE
Use case of nanopb.

### ISSUE THREAD

**Issue by VincentVanG-O-A-T** [nanopb/nanopb#179]
In C, you often have to work with hierarchical data structures using pointers. It can be cumbersome to write "custom" allocators and deallocators for this data on a per-module basis. Is it a valid use case to use protobufs for internal data in the application to avoid this boilerplate?

**Comment by PetteriAimonen** [comment]
I have no idea, really.
Maybe, if it works for the purpose.

Perhaps this would fit better as a discussion on the forum, instead of 
as an issue?

**Comment by VincentVanG-O-A-T** [comment]
Fair enough...
