### ISSUE TITLE
Suppression of has_* fields for protobuf 3

### ISSUE THREAD

**Issue by vvanbeveren** [nanopb/nanopb#182]
In protobuf3 all plain fields are optional. This generates a lot of has_\* fields, which is not desirable in resource constraint environments such as microcontrollers. A way to suppress, or limit, the generation of has_\* for protobuf3 would mean that precious resources are not wasted.

**Comment by kylemanna** [comment]
How would you know if the field was ever set without the `has_*` field in C without metadata like this?

**Comment by PetteriAimonen** [comment]
In proto3, the default value is always zero-ish:
https://developers.google.com/protocol-buffers/docs/proto3#default

So just have to check for those conditions.

Another issue is how to convey to nanopb runtime that we are in proto3 
mode. This should probably be a per-message info somewhere.
I would really like to be able to reuse PB_HTYPE_REQUIRED etc. for 
different purposes in proto3.

**Comment by PetteriAimonen** [comment]
Fixed by #216.

**Comment by PetteriAimonen** [comment]
Fix released in nanopb-0.3.7
