### ISSUE TITLE
Segmentation fault when freeing NULL PB structure

### ISSUE THREAD

**Issue by mottigondabi** [nanopb/nanopb#183]
Segmentation fault happen when calling pb_release() with NULL pointer. This should be avoided as proposed in ANSI C free() for a NULL pointer.

Example:

MyPbStruct {
   string a[12];
   pb_bytes_array_t *p;
}

void foo(void) {
    MyPbStruct  *myTestStruct = NULL;
    pb_release(MyPbStruct_fields, myTestStruct);    // <=== segmentation fault happen right here
  }

--Motti

**Comment by PetteriAimonen** [comment]
Hmm yeah, would make sense to have it work similar to free().

**Comment by PetteriAimonen** [comment]
Fix released in nanopb-0.3.5.
