### ISSUE TITLE
Allow anonymous unions for oneof

### ISSUE THREAD

**Issue by kamathba** [nanopb/nanopb#184]
Would anybody be interested in a way to specify through the .options file that a specific union/message field be an anonymous union/structure? It could just be my own bad design patterns but it seems like something that could be handy to prevent Response.FooResponse.foo_bar_response type field names.

It would maybe be more useful for unions, and would be limited in application to fields only, not native message types.

I might be missing something that would make this tricky but I feel like I could have cleaner generated files if this was an option.

**Comment by PetteriAimonen** [comment]
Shouldn't be too problematic to implement, and there is a similar
enum_short_names option also to clean up the generated names. So
yeah, would make sense to have some anonymous_unions generator
option.

**Comment by PetteriAimonen** [comment]
Implemented by pull request #186.

**Comment by PetteriAimonen** [comment]
Feature released in nanopb-0.3.5.
