### ISSUE TITLE
Add trait types for c++

### ISSUE THREAD

**Issue by eric-wieser** [nanopb/nanopb#232]
For a message like
```protobuf
message MyMessage {
  float number = 1;
}
```

It would be great if the following extra template constants existed

* `static pb_field_t const* const pb_traits<MyMessage>::fields == MyMessage_fields`
*
  * `static int const pb_traits<MyMessage>::tag_v<&MyMessage::number> == MyMessage_number_tag` (C++17)
  * `static int const pb_traits<MyMessage>::tag_v<&MyMessage::number, float> == MyMessage_number_tag` (C++14)
  * `static int const pb_traits<MyMessage>::tag<&MyMessage::number, float>::value == MyMessage_number_tag`
* `static size_t const pb_traits<MyMessage>::max_size == MyMessage_size`
* `static MyMessage const pb_traits<MyMessage>::init_zero == MyMessage_init_zero`
* `static MyMessage const pb_traits<MyMessage>::init_default == MyMessage_init_default`

**Comment by thirtythreeforty** [comment]
You can kinda-sorta approximate this by having a macro that specializes all those traits you specify for a given type name, then just calling the macro with all your NanoPB message types.

I agree that this would be handy though.  I'd like to do some type-safe boilerplate reduction in C++ using traits such as these, and it would be nice to have all of it generated.

Note that they should probably be `constexpr`.

**Comment by vlovich** [comment]
Add a basic kind of thing in #384. Can be used to expand on this request further.

**Comment by eric-wieser** [comment]
Can you give an example of the code yours generates here?

**Comment by PetteriAimonen** [comment]
vlovich's pull request is now included in 0.4.0.
