### ISSUE TITLE
grpc support

### ISSUE THREAD

**Issue by d21d3q** [nanopb/nanopb#235]
I am now testing communication between µC and using via simple protobuf messages and for now I can see that it would be nice to have it defined in grpc style. If it will work fine, I will wrap it in some simple library. 
The question is if it should be part of nanopb, or better make separate project which relays on nanopb?

**Comment by PetteriAimonen** [comment]
I think it would make sense to have grpc support in nanopb. I assume it can relatively easily made so that it is an optional feature (e.g. in a separate pb_grpc.c file or similar).

**Comment by d21d3q** [comment]
[Here](https://github.com/d21d3q/nanopb/tree/dev-grpc) you can see what direction I took in implementing grpc. @PetteriAimonen now I am going to start to work with generator. In [C++ example of grpc](http://www.grpc.io/docs/tutorials/basic/c.html#generating-client-and-server-code) generator is being split into to separate plugins, but in [python example](http://www.grpc.io/docs/tutorials/basic/python.html#generating-client-and-server-code) there is only one plugin. Would be enough if I would add grpc functionality into current generator (and wrap code in `#ifdef PB_ENABLE_GRPC` ... `#endif`), or should I write separate one?

**Comment by PetteriAimonen** [comment]
Seems promising, and reasonable amount of code so far that it could eventually be part of nanopb also.  About the generator, plugin mechanisms may be more trouble than they are worth. But the code could probably be in a separate file that would get imported, if that makes it easier to organize (nanopb_generator.py is getting quite long already).

**Comment by bl0rq** [comment]
How far did this get?  I have a need for this and I would be happy to help push things forward.

**Comment by PetteriAimonen** [comment]
@bl0rq It's now here https://github.com/d21d3q/nanogrpc but I don't know actual status.

**Comment by PetteriAimonen** [comment]
There are currently no plans to implement grpc support in nanopb main code, any support would be a separate project.
