### ISSUE TITLE
pb_decode_varint32 doesn't detect overflow properly?

### ISSUE THREAD

**Issue by vlovich** [nanopb/nanopb#258]
It checks bitpos >= 32 but that value would have already overflowed.

At the beginning of the loop, bitpos = 7 indicates we're going to try to read the 2nd byte.  bitpos=14 indicates we're reading the 3rd.  bitpos = 21 indicates we're reading the 4th.  bitpos = 28 would indicate an overflow, not 32.

**Comment by PetteriAimonen** [comment]
Hmm yeah, it is not an exact check currently. It would need to have extra check whether all the upper bits are zero in the last byte with bitpos = 28. I guess the speed penalty should be pretty small.

**Comment by PetteriAimonen** [comment]
Fix released in nanopb-0.3.9.
