### ISSUE TITLE
example is missing has_field

### ISSUE THREAD

**Issue by prusnak** [nanopb/nanopb#263]
in https://github.com/nanopb/nanopb/blob/master/examples/simple/simple.c#L28 there should be a line

`message.has_lucky_number = true;` just above the line `message.lucky_number = 13;`

**Comment by PetteriAimonen** [comment]
In the `simple.proto` file the lucky_number field is declared as `required`, so it will not have a `has_` field.

**Comment by prusnak** [comment]
Ah, I see.
