### ISSUE TITLE
0.3.8 on mbed

### ISSUE THREAD

**Issue by Kulak** [nanopb/nanopb#269]
FYI

It is not an issue.  I have imported nanopb 0.3.8 release files into mbed platform.  The library  contains files  required to run nanopb generated code:

https://developer.mbed.org/users/sgnezdov/code/nanopb/

I am not sure if there is already one.  I tried to locate and did not find one.

**Comment by PetteriAimonen** [comment]
Ok - I haven't really followed the different package platforms much, there are so many of them.
