### ISSUE TITLE
Pod installation problem

### ISSUE THREAD

**Issue by robertherdzik** [nanopb/nanopb#272]
**Steps to reproduce the issue**
I would like to add to my project pod 'Firebase/Core' pod but unfortunately after `pod install` I get 503 Service Unavailable on nanopb pod. 

<img width="776" alt="screen shot 2017-07-22 at 11 40 13" src="https://user-images.githubusercontent.com/10906921/28490155-2b5b13cc-6ed3-11e7-8c53-485215a2ed67.png">

**Comment by PetteriAimonen** [comment]
My service provider is currently undergoing some maintenance, so the older koti.kapsi.fi url is currently not working.

Does it show who is maintaining the nanopb package there? Perhaps you could notify them to update the url to:
https://jpa.kapsi.fi/nanopb/download/

**Comment by robertherdzik** [comment]
Ok now works :) thanks
