### ISSUE TITLE
Deterministic output / option to suppress timestamp

### ISSUE THREAD

**Issue by ezyang** [nanopb/nanopb#274]
By default, nanopb generates a header with the following contents:

```
/* Generated by nanopb-0.3.9-dev at Tue Aug 22 13:10:44 2017. */
```

This is not good for reproducibility, since it means that every invocation of nanopb will generate different contents. It would be great if there were a way to suppress the timestamp here (or, if I may advocate a bit forcefully, to NOT include it at all.)

**Comment by PetteriAimonen** [comment]
Hmm yeah, might make sense to remove the timestamp completely.

But there is already an option, -T to nanopb_generator.py or `protoc --nanopb_out=-T:.`

**Comment by ezyang** [comment]
Thanks! It is too bad `-T` doesn't show up when you run `protoc --help` with the nanopb plugin

**Comment by PetteriAimonen** [comment]
Yeah, protoc doesn't let plugins to provide their own help text.
