### ISSUE TITLE
Publish Conan package

### ISSUE THREAD

**Issue by shreyasbharath** [nanopb/nanopb#294]
If you haven't heard of [Conan](https://www.conan.io/), it's a C/C++ package manager that is gaining a lot of popularity.

I think it'd be great if every release of Nano Protocol Buffers was automatically published as a new version of a Conan package. It'll make consuming it in other projects really easy, and also updating to newer versions.

**Comment by PetteriAimonen** [comment]
Ok, can you perhaps make a pull request about what would be needed to achieve this?

**Comment by shreyasbharath** [comment]
Sure, I'll create a PR when ready.
