### ISSUE TITLE
Build error due to -fobjc-weak is not supported on the current deployment target

### ISSUE THREAD

**Issue by misaxi** [nanopb/nanopb#307]
Not sure if this is related. But I'm developing an app using Ionic which targets iOS. The specific error I got described in the following issue.

https://github.com/phonegap/phonegap-plugin-push/issues/2183#issuecomment-362780912

**Comment by PetteriAimonen** [comment]
Hmm, nanopb doesn't specify that build option so I assume it's coming from their build configuration.

**Comment by hamath** [comment]
I don't know why this error suddenly happened, but fixed by the following links' way.
Let's try to update build target version in nanopb
https://stackoverflow.com/questions/36147625/xcode-7-3-cannot-create-weak-reference-in-file-using-manual-reference-counting
![image](https://user-images.githubusercontent.com/32663254/35768633-42a6a348-0942-11e8-8685-970b99e0eb85.png)

**Comment by misaxi** [comment]
Thanks @hamath , I was able to build the project by setting the deployment target to iOS 9.0.

Looking forward to the official fixes.

**Comment by Rdbrenna** [comment]
Click the Pods Project in Xcode(Usually at the bottom of the navigator) -> Under Targets, Click "nanopb" -> You will see that the Deployment Default is set to "4.3", Change this to the latest (11.3 for me) and it should be fixed :)

**Comment by PetteriAimonen** [comment]
I think there is nothing to do here on the nanopb side, so I'm closing this off.

**Comment by earthman1** [comment]
I have found that pod update resets the ios deployment target to 4.3. I added the following script to my podfile to reset the deployment target on each update:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
```
Of course, you may choose a different target than 9.0, by changing the target number in the above script.
