### ISSUE TITLE
network_server printfile_callback is error

### ISSUE THREAD

**Issue by Zhangjd1028** [nanopb/nanopb#317]
typedef struct _FileInfo {
    uint64_t inode;
    pb_callback_t name;
/* @@protoc_insertion_point(struct:FileInfo) */
} FileInfo;

 the name is a function for callback, so you demo can't print the name. and i don't know how to decode the bytes or string type tag data , can you give me a demo ?

**Comment by PetteriAimonen** [comment]
Sounds like the `fileproto.options` file is not being found for some reason. Make sure that it is in the same directory as fileproto.proto when you run the nanopb generator.

With the .options file in place it gives for me:

<pre>
typedef struct _FileInfo {
    uint64_t inode;
    char name[128];
/* @@protoc_insertion_point(struct:FileInfo) */
} FileInfo;
</pre>
