### ISSUE TITLE
All callbacks are set to NULL。Why？

### ISSUE THREAD

**Issue by teldyc** [nanopb/nanopb#318]
In pb_decode. c line 463~469 , I see that you set all callbacks to NULL.Why would you do that? Any thoughts?I block this code, make my code work normally, is there any hidden trouble?Thanks!

**Comment by PetteriAimonen** [comment]
This is done for oneof messages, because the message storage overlaps. If you have multiple messages with callbacks inside the oneof, setting the callbacks for the second message would overwrite the callbacks for first message with garbage and result in a crash.

Related: issue #175

**Comment by teldyc** [comment]
Great！Many thanks！
