### ISSUE TITLE
Add documentation for generator command line options to the docs

### ISSUE THREAD

**Issue by Amomum** [nanopb/nanopb#319]
I added custom build step to my build system that regenerates .c and .h files for my .proto file.
Unfortunately, nanopb puts this comment with current time and date in them :
```
/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Mon Mar 26 19:15:47 2018. */
```
That makes git sad because files change on every build.

Is it possible to stop this comment from generating?

**Comment by PetteriAimonen** [comment]
Yeah, use option `-T`, for example:

<pre>
nanopb_generator.py -T ...
</pre>

or if used through protoc:

<pre>
protoc --nanopb_out=-T:outdir ...
</pre>

**Comment by Amomum** [comment]
Oh, that's great!
I searched in the docs but didn't find that option there. Is it mentioned there?

**Comment by PetteriAimonen** [comment]
I guess not; -h to the generator shows some help.
