### ISSUE TITLE
Compile problem with Keil

### ISSUE THREAD

**Issue by turbinetim** [nanopb/nanopb#327]
Hi,

When trying to add a function for a callback on a encode (in Keil), with the current 0.3.9.1 release, I receive a compile error:

..\collar-source\datastructs\kaddz_data.c(139): error:  #513: a value of type "_Bool (*)(pb_ostream_t *, const pb_field_t *, const void *)" cannot be assigned to an entity of type "union <unnamed>"

My callback is defined as follows:

bool KADDZ_Encode_Wifi_Information(pb_ostream_t *stream, const pb_field_t messagetype[], void const *message) {

Am I missing something obvious like a pragma or something?

Thanks
Tim

**Comment by PetteriAimonen** [comment]
Answered on forum: https://groups.google.com/forum/?fromgroups#!topic/nanopb/ly_s21X5I9Q
