### ISSUE TITLE
Add #define'd constant for length of string fields when using max_size

### ISSUE THREAD

**Issue by sefx** [nanopb/nanopb#330]
When creating a string field that has a static length via max_size in the .options file, e.g.:
```
# Foo.options
Foo.name max_size:16
```
...the resulting .h file should include some #define'd constant for the field's length, along the lines of:
```c
#define Foo_name_max_size 16

typedef struct _Foo {
    char name [Foo_name_max_size];
} Foo;
```
This constant would be a useful argument to ```strncpy```, for example.  Being able to reference the nanopb-generated .h file would mean the constant would be in sync with the protocol definition and reduce the chance for errors due to ```strncpy``` argument being incorrect.

**Comment by PetteriAimonen** [comment]
Would using `pb_membersize(Foo, name)` be ok?

If you have an instance of the structure, you can also use `sizeof(foo.name)`.
