### ISSUE TITLE
Possible bug in the encoded size of Xint32 and Xint64.

### ISSUE THREAD

**Issue by BartHertog** [nanopb/nanopb#332]
Hi,

Working with nanopb I have found a possible bug in the encoded size of Xint32 and Xint64. 

**Steps to reproduce the issue**

1. We where using an array of doubles. To reduce the memory and computation footprint we changed the double it to an int32. To our surprise the memory required increased! You can check this the example proto and config files listed at the bottom of the ticket.
2. These commands where used to build using nanopb-0.3.9.1:
```
protoc -o size_test.pb size_test.proto
python nanopb_generator.py size_test.pb
```

**What happens?**
These expected sizes are generated:
```
/* Maximum encoded size of messages (where known) */
#define test_int32_size                          11
#define test_int64_size                          11
#define test_float_size                          5
#define test_double_size                         9
#define test_array_int32_size                    110
#define test_array_int64_size                    110
#define test_array_float_size                    50
#define test_array_double_size                   90
```

**What should happen?**
I would expect a int32 to have the size of 4 bytes and a int64 8 bytes.

Looking at nanopb_generator.py I found the map below. As you can see INT32 and INT64 are both defined as 10. Is this correct?

Looking at this code I also cannot understand the sizes of SINTXX and UINTXX, should these not be 4 and 8 as well?

nanopb_generator.py:
```
datatypes = {
    FieldD.TYPE_BOOL:       ('bool',     'BOOL',        1,  False),
    FieldD.TYPE_DOUBLE:     ('double',   'DOUBLE',      8,  False),
    FieldD.TYPE_FIXED32:    ('uint32_t', 'FIXED32',     4,  False),
    FieldD.TYPE_FIXED64:    ('uint64_t', 'FIXED64',     8,  False),
    FieldD.TYPE_FLOAT:      ('float',    'FLOAT',       4,  False),
    FieldD.TYPE_INT32:      ('int32_t',  'INT32',      10,  True),
    FieldD.TYPE_INT64:      ('int64_t',  'INT64',      10,  True),
    FieldD.TYPE_SFIXED32:   ('int32_t',  'SFIXED32',    4,  False),
    FieldD.TYPE_SFIXED64:   ('int64_t',  'SFIXED64',    8,  False),
    FieldD.TYPE_SINT32:     ('int32_t',  'SINT32',      5,  True),
    FieldD.TYPE_SINT64:     ('int64_t',  'SINT64',     10,  True),
    FieldD.TYPE_UINT32:     ('uint32_t', 'UINT32',      5,  True),
    FieldD.TYPE_UINT64:     ('uint64_t', 'UINT64',     10,  True)
}
```

**Example code***

size_test.proto
```
syntax = "proto3"; 

message test_int32 {
    int32 x = 1;
}

message test_int64 {
    int64 x = 1;
}

message test_float {
    float x = 1;
}

message test_double {
    double x = 1;
}


message test_array_int32 {
    repeated int32 x = 1;
}

message test_array_int64 {
    repeated int64 x = 1;
}

message test_array_float {
    repeated float x = 1;
}

message test_array_double {
    repeated double x = 1;
}
```

size_test.options
```
test_array_int32.x max_count:10
test_array_int64.x max_count:10
test_array_float.x max_count:10
test_array_double.x max_count:10
```

**Comment by PetteriAimonen** [comment]
Yes, maximum encoded size 10 for int32/int64 is correct. This is due to how protobuf encodes the values: https://developers.google.com/protocol-buffers/docs/encoding#varints

A -1 in int32 field gets turned into 64-bit 0xFFFFFFFFFFFFFFFF which takes 10 bytes to encode in the varint format. With the field header, this becomes 11 bytes.

You can check with protoc:

    petteri@oddish:~$ echo 'x: -1' | protoc --encode=test_int32 size_test.proto | wc -c
    11

For negative values, `sint32` and `sint64` are more efficient.
