### ISSUE TITLE
the bytes memcpy the unsigned char buffer the length is not correct

### ISSUE THREAD

**Issue by Tingting-He** [nanopb/nanopb#348]
I define the bytes obj,the length is 1.5M,and I have the unsigned char buffer[] length also is 1.5M.
the buffer is stored the video data,when I memcpy(output.obj.bytes,buffer,strlen(buf)),the output.obj.size is 39,but the strlen(buf) is 1770812,it's about 1.2M.
why?who know the probles?thanks.

**Comment by PetteriAimonen** [comment]
For bytes fields, there is generated field `output.obj.bytes.size`. You must set this to the length of the data, i.e. to `strlen(buf)`.

(Also consider whether your data is binary data or text data, i.e. can it contain '0' bytes. The C standard function `strlen()` only works for text.)

**Comment by Tingting-He** [comment]
first,thankyou.
the define bytes obj is like belows
typedef PB_BYTES_ARRAY_T(2097152) upload_video_param_obj_t;
typedef struct _upload_video_param {
    char device_id[16];
    int32_t frame_total;
    int32_t frame_no;
    upload_video_param_obj_t obj;
    bool is_final;
    char event_ts[16];
/* @@protoc_insertion_point(struct:upload_video_param) */
} upload_video_param;

and copy the binary data to the unsigned char buffer,likes below

HI_U32 i ,j;
      int len = 0;
	  unsigned char * *pstr;
	  unsigned char *p = NULL;
	  p = ntc->threads[ntt].nlc.buf+ntc->threads[ntt].nlc.datalen;
	  for (i = 0; i < pstStream->u32PackCount; i++)
      {
	        memcpy(p, pstStream->pstPack[i].pu8Addr+pstStream->pstPack[i].u32Offset,pstStream->pstPack[i].u32Len-pstStream->pstPack[i].u32Offset);
	        len = len + pstStream->pstPack[i].u32Len-pstStream->pstPack[i].u32Offset;
			pstr = pstStream->pstPack[i].pu8Addr+pstStream->pstPack[i].u32Offset;
			if(pstr[4] == 0x67)
			{
				UpdateSps(p+len, 14);
			}
			if(pstr[4] == 0x68)
			{
				UpdatePps(p+len, 4);
			}
			
      }

	  ntc->threads[ntt].nlc.datalen += len;


then copy the buffer binary data to the obj.bytes,the length correct

memcpy(response.obj.bytes,nlc->buf,nlc->datalen);

but when I save the buffer binary data to file,fread from file to the obj.bytes,the size is right.
response.obj.size = fread(response.obj.bytes,1,NET_FILE_DATA_LEN,f);
oh my gard.

**Comment by PetteriAimonen** [comment]
I couldn't understand your message. Is it working now?

**Comment by Tingting-He** [comment]
>           I couldn't understand your message. Is it working now?

It is not working now，sample like below:
unsigned char *p = nlc->buf; //the video binary data
unsigned int p_len = nlc->datalen; //the p_len < 2*1024*1024
unsigned char sendbuf[2*1024*1024] = {0};
unsigned int sendbuf_len = 0;

memset(sendbuf,0,2*1024*1024);
upload_video_param response = {};
pb_ostream_t output = pb_ostream_from_buffer(sendbuf,2*1024*1024);
memcpy(response.obj.bytes,p,p_len);
if (!pb_encode(&output, upload_video_param_fields, &response))
{
	  printf("Encoding failed: %s\n", PB_GET_ERROR(&output));
}

the response.obj.size is 0, I have no idear for the question.

**Comment by Tingting-He** [comment]
>           I couldn't understand your message. Is it working now?
It is now working. I add response.obj.size = p_len; before the memcpy(response.obj.bytes,p,p_len),like below:
unsigned char p = nlc->buf; //the video binary data
unsigned int p_len = nlc->datalen; //the p_len < 210241024
unsigned char sendbuf[2*1024*1024] = {0};
unsigned int sendbuf_len = 0;
memset(sendbuf,0,2*1024*1024);
upload_video_param response = {};
pb_ostream_t output = pb_ostream_from_buffer(sendbuf,2*1024*1024);
response.obj.size = p_len;
memcpy(response.obj.bytes,p,p_len);
if (!pb_encode(&output, upload_video_param_fields, &response))
{
printf("Encoding failed: %s\n", PB_GET_ERROR(&output));
}
