### ISSUE TITLE
Encode/Decode sub messages without callbacks

### ISSUE THREAD

**Issue by masoudr** [nanopb/nanopb#364]
Hi,
I'm new to `nanopb`. I'm trying to create a simple example with nested messages but It seems that encoding is fine but when I want to decode it I get `end-of-stream` error. If I understand correctly I only need callbacks if I define reapeated messages or undefined string size message. Is my encoding steps is correct? How about decoding which one should I decode first submessages (child) or main message?
Thanks.
Suppose this example:
```
# my_sample.proto
message MainMessage {
    message Child {
        required int32 a = 1;
        required int32 b = 2;
    }
    // if I use required it works fine, but for optional I get issue 
    optional Child child = 1;
}

```

```
void decode(uint8_t *input, size_t message_length)
{
    MainMessage msg = MainMessage_init_zero;
    pb_istream_t stream = pb_istream_from_buffer(input, message_length);
    bool status = pb_decode(&stream, MainMessage_Child_fields, &msg.child);
    if (!status)
    {
        printf("Decoding failed: %s\n", PB_GET_ERROR(&stream));
        return;
    }
    status = pb_decode(&stream, MainMessage_fields, &msg);
    if (!status)
    {
        printf("Decoding failed: %s\n", PB_GET_ERROR(&stream));
        return;
    }
    printf("Message decoded a: %d, b:%d\n", msg.child.a, msg.child.b);
}


void encode()
{
    MainMessage msg = MainMessage_init_zero;
    msg.child.a = 1;
    msg.child.b = 2;
    uint8_t buffer[128] = {0};
    size_t message_length = 0;
    bool status;
    pb_ostream_t stream = pb_ostream_from_buffer(buffer, sizeof(buffer));


    if (! pb_encode_submessage(&stream, MainMessage_Child_fields, &msg.child)){
        printf("pb_encode_submessage Failed!\n");
        return;
    }

    if (!(status = pb_encode(&stream, MainMessage_fields, &msg)))
    {
        printf("pb_encode Encoding failed: %s\n", PB_GET_ERROR(&stream));
        return;
    }
    message_length = stream.bytes_written;
    printf("buffer: ");
    for (int i = 0; i < sizeof(buffer); i++)
    {
        if (buffer[i])
            printf("%d, ", buffer[i]);
    }
    printf("\nmessage_length: %d\n", message_length);
    decode(buffer, message_length);
}

int main()
{
    encode();
}
```
Thanks.

**Comment by PetteriAimonen** [comment]
You don't need to separately encode/decode the submessage.

Just the parts that encode the mainmessage is enough, the submessage will automatically be encoded as part of it.

**Comment by masoudr** [comment]
@PetteriAimonen I already tried that but after decoding the values for sub-messages is all default ones. I edited the main code I get zeroes for `a` and `b`.

**Comment by PetteriAimonen** [comment]
For optionals, you need to set has_child = true.

**Comment by masoudr** [comment]
@PetteriAimonen Thanks, but where should I add this param? Can you give me an example?

**Comment by uraj** [comment]
@masoudr Check out [this](https://jpa.kapsi.fi/nanopb/docs/reference.html#proto-file-options).

**Comment by masoudr** [comment]
@uraj I still can't get it. Do you mind adding it to my current example?

**Comment by uraj** [comment]
@masoudr Sorry my previous comment was wrong. I've edited it. Check it out.

**Comment by masoudr** [comment]
@uraj Thanks. Do I need to set it for encoding too?

**Comment by uraj** [comment]
You set it only for encoding. When decoding, the decoder sets it for you so you know whether the incoming message contains the optional or not.

**Comment by masoudr** [comment]
Can you tell me what option should I set when I use a `repeated` field? It seems that there is no option with `has_...` for the repeated fields.

**Comment by PetteriAimonen** [comment]
Don't be afraid to look inside the generated .pb.h files. You'll find a "field_count" field there.
