### ISSUE TITLE
Proper way to send an encoded data

### ISSUE THREAD

**Issue by masoudr** [nanopb/nanopb#368]
Hi,
I'm trying to send an encoded buffer (array of `unsigned char`) from a server to a client with an http request. My first attempt was to convert the array of `unsigned char` to equivalent ASCII string and then send throw the network. for example, suppose this buffer:

    unsigned char buffer[] = {72, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 0, 24, 1, 32, 1, 40, 0};
And if I convert it to a string I would have this:

> Hello world  (

which has null terminating chars and I have problems on the client side to read it back because I can't find the end of the message and reconstruct the buffer. Is there any way to create a string from ProtoBuf output with minimal length?
I found that there is `SerializeToString` in ProtoBuf but it is missing in NanoPB.

**Comment by PetteriAimonen** [comment]
I see you've already asked the same question on StackOverflow ( https://stackoverflow.com/questions/53736331/input-string-consists-of-null-terminating-chars ).

Please wait to see if the answers you get there help you forwards.

Even `SerializeToString` in C++ protobuf library will have null bytes in the string. C++ strings can store null bytes, while C strings cannot. Encoded protobuf data is always binary data and you have to treat it as such, i.e. don't use string functions on it.

**Comment by masoudr** [comment]
@PetteriAimonen OK, but what is the proper way to send them over a network?

**Comment by PetteriAimonen** [comment]
https://github.com/nanopb/nanopb/tree/master/examples/network_server  For example like this example does it.

**Comment by masoudr** [comment]
@PetteriAimonen I saw that example but can't understand how you send an `unsigned char` array, can you explain a little bit?
@KidVizious Thank you it is a good idea but I don't have enough resource to encode to base64.

**Comment by KidVizious** [comment]
@masoudr Obviously, I don't know your resource requirements, but you can Base64 encode with about 50 lines of code.

**Comment by masoudr** [comment]
@KidVizious Thanks, sure I will give it a shot.
