### ISSUE TITLE
Overriding int_size does not affect maximum size of messages

### ISSUE THREAD

**Issue by MarioRose** [nanopb/nanopb#373]
Hi,

as discussed in https://groups.google.com/forum/#!topic/nanopb/ZcqcUaY5UVo

**Comment by PetteriAimonen** [comment]
Note to self: the fix doesn't backport easily to 0.3.9.x and it is kind of low priority, so I'll leave this for 0.4.0.

**Comment by unsignedint** [comment]
This is actually a problem that we have hit on a project I am are working on (as we now start to optimise memory usage), I can confirm the fix in git works... any idea on when we could expect 0.4.0?

**Comment by PetteriAimonen** [comment]
In a few months perhaps. There are some infrastructure problems I need to fix first before I have enough confidence in it, because the AVR & ARM test envs haven't been working lately.

**Comment by shreyasbharath** [comment]
Looking forward to this fix!

**Comment by PetteriAimonen** [comment]
Well, you can start using the master branch already. Binary packages are available here: http://jpa.kapsi.fi/jenkins/job/nanopb-binary-windows/
