### ISSUE TITLE
Repeated field improperly using data of first array element as size of array

### ISSUE THREAD

**Issue by eg9152** [nanopb/nanopb#376]
For a fixed repeated field, size_offset is set to 0 (pb.h:534).  pSize is then used as pData + size_offset in pb_check_proto3_default_value (pb_encode.c:219).  *pSize is then used (pb_encode.c:229).  pSize points to the first data element of the array.  If the first data element is zero, then field does not get included.

However, this only happens when the repeated field is in a submessage such as in the attached example.  (Otherwise pb_check_proto3_default_value isn't called.)

Attachment is from the "simple" nanopb included example, modified, and thus uses nanopb.mk.

One other bit of information is that in pb_encode.c:324, where pb_check_proto3_default_value is called, field->size_offset will always equal 0 when it is called based on the "if" condition.

[repeated_field_issue.tar.gz](https://github.com/nanopb/nanopb/files/2810845/repeated_field_issue.tar.gz)

**Comment by PetteriAimonen** [comment]
Looks like the current git master is not affected due to the changes made in field representation, but it's worth it to backport the fix to 0.3.9.x.

**Comment by PetteriAimonen** [comment]
Fix released in nanopb-0.3.9.3.
