### ISSUE TITLE
oneof filed does not support string type

### ISSUE THREAD

**Issue by xuegangxia** [nanopb/nanopb#389]
`syntax = "proto2";

 message Dimension {
    oneof value {
      int64 dim_value = 1;
      string dim_param = 2; 
    };
 }`

nanopb does not support string type in oneof

**Comment by PetteriAimonen** [comment]
Try specifying a maximum size for the string field, like in here:
https://github.com/nanopb/nanopb/blob/master/tests/oneof/oneof.proto#L24

**Comment by xuegangxia** [comment]
thanks for answer my question so quickly , It works
