### ISSUE TITLE
DeprecationWarning: 'U' mode is deprecated

### ISSUE THREAD

**Issue by ooxi** [nanopb/nanopb#399]
When using nanopb I receive the following deprecation warning from [nanopb_generator.py](https://github.com/nanopb/nanopb/blob/master/generator/nanopb_generator.py#L1712)

```
DeprecationWarning: 'U' mode is deprecated
  Globals.separate_options = read_options_file(open(optfilename, "rU"))
```

How can we fix this warning? Unfortunately I'm not familiar enough with Python to fix it myself.

I'm using Arch Linux with Python 3.7.3

---

*Update:* According to the [Python documentation](https://docs.python.org/3/library/functions.html?highlight=open#open) the `U` modifier now longer has an effect

> There is an additional mode character permitted, 'U', which no longer has any effect, and is considered deprecated. It previously enabled universal newlines in text mode, which became the default behaviour in Python 3.0. Refer to the documentation of the newline parameter for further details.

**Comment by PetteriAimonen** [comment]
Hmm, it will need some check for Python 2 vs. Python 3. It is unfortunate that they've added that warning in Python 3, as it was easier to make code portable between the Python versions without it.

The fix would probably be to assign `openmode = 'rU'` vs. `openmode = 'r'` in the existing check on line 119.

For now you can ignore the warning.

**Comment by ooxi** [comment]
Thanks for the feedback! I did not consider Python 2 ./. compatibility
