### ISSUE TITLE
pip-package for generator plugin

### ISSUE THREAD

**Issue by kaspar030** [nanopb/nanopb#401]
I'm currently working on integrating nanopb as a package into [RIOT](https://github.com/RIOT-OS/RIOT/pull/11565).
While writing the corresponding README on how to get started with nanopb, I realized that getting the generator installed requires quite a lot more manual work.

Isn't the generator basically a python application? It could be made installable via "pip".

If there's interest, I can try PR'ing something.

**Comment by PetteriAimonen** [comment]
Hmm, that's actually a great idea. I've never thought about it before, but it makes perfect sense.

I don't have much time to work on it in the near future, so if you can make a PR that would be great!
