### ISSUE TITLE
decode the element message without field name

### ISSUE THREAD

**Issue by niexuzhong** [nanopb/nanopb#410]
I have such message structure like following
 message xxx {
       int32 a = 1;
    oneof bmod {
        typea c = 2;
        typeb  d = 3;
    }
   message typea {
      bytes   values =1
    }
   message typeb {
     repeated int32 f=1
    }
}
the generate data structure like following
typedef struct xxx {
    int32_t  a;
    pb_size_t which_module;
    union {
        typea b;
        typeb c;
    } bmod;
} xxx;
typedef struct xx {
    pb_callback_t values;
} xx;
typdef struct xx {
  pb_callback_t  f;
}xx;
 because the call back couldn't be called in union for C language. So I have to use the method described in samples about union to decode the  values and f, the values and f can be decoded normal, for next step i want to use pb_decode(&istream,xxfield,&xxx) to decode a element, but a doesn't have standalone field so how can I decode it?for the encode, it has same problem. how can we encode the a element? Can you give me some advices about it? Thank you!

**Comment by PetteriAimonen** [comment]
Sorry about not responding earlier, but I can't really understand at all what you are asking.
