### ISSUE TITLE
Allow for "has" field in generated structure to be true/false in #define

### ISSUE THREAD

**Issue by ricardoaiglesias** [nanopb/nanopb#423]
**What should the feature do?**
In addition to allowing the author of a nanopb to declare a default value, this feature would be able to specify whether the field should be included by default or not. 

An example of this in action would be:

```
message DataMessage { 
  optional  State state = 1 [(nanopb).default_has = true] ;
  /* potentially more fields here */
}

```
Where _State_ may contain sub-fields within it. 

This, in turn, could compile to the following structure
```
/* Struct definitions */
typedef struct _DataMessage {
    bool has_state;
    State state;
} DataMessage;

/* Initializer values for message structs */
#define DataMessage_init_default                 {true, State_init_default};
```

**In what situation would the feature be useful?**
I am currently working on a project where it's useful to initialize all of a message's `has_` fields to true (in both the top-level message and all submessages), but then subsequently be able to set the `has_` boolean to false to avoid serializing that part of the protocol buffer and sending it over a transmission protocol.

**Comment by PetteriAimonen** [comment]
Sounds reasonable.
