### ISSUE TITLE
I have a question regarding the version.

### ISSUE THREAD

**Issue by soimsoim** [nanopb/nanopb#424]
I have a question regarding the version.

In cocoapods the version is 0.3901 for tag: 0.3.9.1. (https://github.com/CocoaPods/Specs/blob/master/Specs/6/1/e/nanopb/0.3.901/nanopb.podspec.json)
Is the official version 0.3.9.1 or 0.3.901 for that version?

**Comment by PetteriAimonen** [comment]
0.3.9.1 is the version number I use, but I don't know who maintains the CocoaPods specs for it.
