### ISSUE TITLE
add option to not encode scalar arrays as packed

### ISSUE THREAD

**Issue by prusnak** [nanopb/nanopb#426]
Due to https://github.com/nanopb/nanopb/blob/95d614263cdb1cca3af26a9f2f7b02072e99eb0f/pb_encode.c#L121 it is not possible to send unpacked arrays of scalar datatypes.

There are still some codebases stuck on the old version of protobuf.js which does not recognize packed arrays (see https://github.com/protobufjs/protobuf.js/issues/432).

It would be nice to have an option to override this setting (which essentially changes the condition above to `if (0)`). I have tested this change in my codebase and this modified code correctly produces the unpacked scalar arrays which older protobuf.js has no trouble parsing.

**Comment by PetteriAimonen** [comment]
Hmm, I guess it would be ok to have a compile-time `#ifdef` for that.

**Comment by prusnak** [comment]
Sure, I am fine with an `#ifdef`. Will send a PR if you want.
