### ISSUE TITLE
Does nanopb support automatically filling structs?

### ISSUE THREAD

**Issue by wgaylord** [nanopb/nanopb#430]
On the google ProtoBuf the structures used to represent the data are automatically filled on Decode. With nanopd this struct has values of type pb_callback_t instead of the expected value type. (Example a string).

Or is this a short falling on nanopb being so small?  If this is the case is there a way to automatically generate these callbacks instead of having to basically code the whole protocol.  (What I use to do before using ProtoBuf)

**Comment by wgaylord** [comment]
Is there a way to define the type for all fields of a protocol with out having to define each one? Or is it best to define each one. (Memory is not a big problem as I am running on an ESP32)

**Comment by PetteriAimonen** [comment]
> Is there a way to define the type for all fields of a protocol with 
> out having to define each one? Or is it best to define each one. 

Sure, just use * in the .options file.

https://jpa.kapsi.fi/nanopb/docs/reference.html#defining-the-options-in-a-options-file

**Comment by wgaylord** [comment]
I managed to make all my fields be pointers. I can't seem to figure out how to actually get them to decode. Seems pb_decode does not fill the structure with the data from the stream.

**Comment by PetteriAimonen** [comment]
Have you enabled PB_ENABLE_MALLOC at compile time?

**Comment by wgaylord** [comment]
Yes and it seems that the pb_decode call fails (Returns 0) and the struct is left in the initialized state.

**Comment by wgaylord** [comment]
Seems my length of the packet was byteswapped. Should have checked at before. (Was fine before but moving to an ESP32 changed that somehow).
