### ISSUE TITLE
Coverity issue: Out-of-bounds read at file pb_encode.c

### ISSUE THREAD

**Issue by jsantana-broadsoft** [nanopb/nanopb#435]
Hello,

We run Coverity analysis tool in our code base and a Out-of-bounds read issue was reported in file pb_encode.c file. 

I am attaching a screenshot of the issue details from the Coverity tool. I hope it provides enough details. 

First part of screenshot:
![image](https://user-images.githubusercontent.com/13836740/66229931-98905200-e6a8-11e9-8420-2f3e49384897.png)

Second part of screenshot:
![image](https://user-images.githubusercontent.com/13836740/66229792-3cc5c900-e6a8-11e9-85b5-bb41588b6bd1.png)

Thanks!

**Comment by PetteriAimonen** [comment]
That would only happen with invalid field descriptors (PB_HTYPE_ONEOF without pSize).

But the logic is needlessly complicated there, it has been cleaned up in current master branch.

**Comment by jsantana-broadsoft** [comment]
Thank for the reply. I see the implementation of that method in master change substantially. 

We are not using it directly, it seems several Google frameworks are using it, Firebase specifically. For some reason, Firebase is using a 0.3.9011 version of nanopb.

I think we have to wait until they move up to a newer nanopb to get that issue resolved. 

Thanks!
