### ISSUE TITLE
Optional Fields in repeated field

### ISSUE THREAD

**Issue by DonFreeze** [nanopb/nanopb#439]
Is it possible to have optional fields in a repeated one?
I'm asking, since I run into error in my decoding callback function.

message Object 
{
   optional Objext_X objext_x = 1;
   optional Objext_Y objext_y = 2;
   optional Objext_Z objext_z = 3;
}

message Config
{
    repeated Object objects = 1;
}

**Comment by PetteriAimonen** [comment]
Yeah, should work fine. What error are you getting?

**Comment by DonFreeze** [comment]
The pb_decode of the callback function returns a end-of-stream.

**Comment by DonFreeze** [comment]
I double checked my my whole setup and found an error in the encoder :D
Nevertheless, thanks for your fast support :-)
