### ISSUE TITLE
iOS App Store publishment fails: ITMS-90338 - Non-public API usage

### ISSUE THREAD

**Issue by shatk0vskiy** [nanopb/nanopb#448]
<img width="744" alt="Screenshot 2019-10-31 at 03 26 22" src="https://user-images.githubusercontent.com/5717621/67911165-400c8180-fb8e-11e9-84e8-ec52cfcb8162.png">
Someone came across that?

**Comment by PetteriAimonen** [comment]
Sounds like Apple uses nanopb internally, and the symbol names conflict.

Currently nanopb doesn't have a way to easily rename the symbols, but there are a few options you could explore:

- Stripping the private symbols after compilation. If you have nanopb linked in your own application, there is no need to expose those symbols in the final binary. https://stackoverflow.com/a/18226723 seems like a good start.

- Making a huge list of `#define`'s that would rename nanopb symbols at compile time. That could probably made with some kind of `grep -o 'pb_[a-z_]*' *.h | sed ...something ... | sort | uniq | xargs -n 1 printf '#define %s xyz_%s'` script, and then put into `pb_syshdr.h`.

**Comment by khambir** [comment]
@shatk0vskiy may you help me, what was the solution for this issue?
