### ISSUE TITLE
Append "f" to float defaults

### ISSUE THREAD

**Issue by bolind** [nanopb/nanopb#453]
Strict compilation of nanopb generated code results in warnings in the case of float defaults.

Currently generated code:
`const float bar_foo_default = 0.17;`

Desired code:
`const float bar_foo_default = 0.17f;`

This can be tested by compiling with -Werror=float-conversion

See also this Google Groups discussion: https://groups.google.com/forum/#!topic/nanopb/qTn_RNuA--I

**Comment by bolind** [comment]
Could this be as simple as: https://github.com/bolind/nanopb/commit/3a0abc23b01e1953019582fa58c24e38eca4df29

**Comment by PetteriAimonen** [comment]
Looks like it is! Thanks, this is merged now and I added also a test case.
