### ISSUE TITLE
nanopb continues to compile if options have unmatched fields

### ISSUE THREAD

**Issue by wmmc88** [nanopb/nanopb#456]
`Following patterns in <filename>.options did not match any fields: <list of field names>`

If you specify options on a certain field name, and the generator cannot find it, it will print the above message, however the compilation process continues and files are still produced. I believe the correct behaviour should be for the process to terminate after that error message. If someone were to rename a field in their .proto file, and forget to do the equivalent rename in their .optiosn file, they would still get a compiled output, but with incorrect options.

**Comment by PetteriAimonen** [comment]
Well, generally that would result in a compile-time error when compiling the C files.

But it is a reasonable feature to have available via some `--error-on-unmatched` option to the generator. I probably won't be implementing it any time soon, but pull requests are welcome.

**Comment by wmmc88** [comment]
I'm not sure how this would result in a compile time error?

**Comment by PetteriAimonen** [comment]
That depends on the exact options used, but in many cases it will affect the field type, which would end up as an error in C.
