### ISSUE TITLE
Use Python version of protoc from grpc.tool.protoc

### ISSUE THREAD

**Issue by PetteriAimonen** [nanopb/nanopb#462]
Currently using nanopb generator requires installing Python-based nanopb_generator, protobuf-python library and the C++ protoc. In #460 nanopb_generator was made installable using `pip install nanopb_generator` and it also brings in protobuf-python as a dependency. But protoc still needs to be installed separately.

There exists a Python version of the protoc generator and it is available in `grpcio-tools` package. Using this the C++ binary dependency could be dropped entirely.

It would make sense that `nanopb_generator` when invoked directly could take `.proto` files and transparently pass them through grpc.tool.protoc. This would simplify running the generator a lot.

Some more details in #461 comments.

**Comment by theunkn0wn1** [comment]
Been looking into this on my downstream project, using the `grpc-tools` protoc is straight-forward.

Here is an excerpt of how im wrapping protoc to generate sources

```py
from grpc_tools import protoc
...
def arduino_build(ctx):
    # protoc.main expects a list of arguments
    protoc_args = [
        "protoc",
        f"-I={ctx.obj.include_path.absolute()}",  # include path seems to be necessary
        f"--nanopb_out={ctx.obj.output_path.absolute()}",  # output path
        f"empty.proto",  # files we want to build go here (in the downstream this is procedural, shortened for brevity.
    ]
    ...
    # Invoke protoc.
    protoc.main(protoc_args)  # invokes grpc.tools.protoc to generate sources
```
