### ISSUE TITLE
SyntaxWarning: invalid escape sequence \*

### ISSUE THREAD

**Issue by prusnak** [nanopb/nanopb#467]
Running `nanopb_generator.py` on Python 3.8 show the following warning:

```
nanopb_generator.py:1650: SyntaxWarning: invalid escape sequence \*
```

The line in question is this one:

https://github.com/nanopb/nanopb/blob/70f0de9877b1ce12abc0229d5df84db6349fcbfc/generator/nanopb_generator.py#L1650

It seems the correct way how to quote an asterisk is either `r"\*"` or `"\\*"`, but I am not sure, honestly.

**Comment by theunkn0wn1** [comment]
With python its generally correct to use `r""` when dealing with regex strings, as regex tends to look like escape characters to python if you don't escape them properly.
