### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by aep** [nanopb/nanopb#470]
according to the README, the binary release is supposed to be straight forward

```
generator-bin/protoc --nanopb_out=. myprotocol.proto
```

there is no generator-bin, so i'm assuming its   ./generator/protoc   ,  but that doesnt work

```
aep@stark: ~/Downloads/nanopb ./generator/protoc 

         ********************************************************************
         *** Failed to import the protocol definitions for generator.     ***
         *** You have to run 'make' in the nanopb/generator/proto folder. ***
         ********************************************************************
    
Traceback (most recent call last):
  File "./generator/protoc", line 4, in <module>
    from nanopb_generator import invoke_protoc
  File "/home/aep/Downloads/nanopb/generator/nanopb_generator.py", line 42, in <module>
    from .proto import nanopb_pb2
ImportError: attempted relative import with no known parent package

```

note that doing what the fat warning says, has no effect

```
aep@stark: ~/Downloads/nanopb/generator/proto make
make: Nothing to be done for 'all'.

```

**Comment by PetteriAimonen** [comment]
Hmm, if there is no `generator-bin`, it sounds like you have the plain source package instead of the linux binary package.

But even then, it should work the way you call it if you happen to already have either binary protoc or grpcio-tools Python package installed. The error you received seems to occur only with Python 3. I have fixed it now in revision 96670da.

**Comment by aep** [comment]
i dunno what i did with the binary, but your latest commit fixes it with from-source builds, thanks

**Comment by PetteriAimonen** [comment]
I'll reopen this until fix is released, to make it easier to find for others hitting the same problem.
