### ISSUE TITLE
Build error for missing uint8_t type in pb_decode.c

### ISSUE THREAD

**Issue by markuslindroth** [nanopb/nanopb#485]
When compiling pb_decode.c for a platform without uint8_t, I get error. There is one line with uint8_t

`uint8_t sign_extension = (bitpos < 63) ? 0xFF : 0x01;`

The other uint8_t in this file were replaced by pb_byte_t a couple of years ago, and this line was added after that.

**Comment by PetteriAimonen** [comment]
Fixed now and added a basic check, that just does a grep for int8_t / uint8_t in the core source files.

For a proper testcase I'd need to find a platform that lacks 8-bit types but has easily available compiler and simulator.
