### ISSUE TITLE
Error at Xcode 11.4 beta

### ISSUE THREAD

**Issue by nebiros** [nanopb/nanopb#488]
I install this via CocoaPods, here's the version also:

```
- nanopb (0.3.9011):
    - nanopb/decode (= 0.3.9011)
    - nanopb/encode (= 0.3.9011)
```

Here's the error:

```
ld: -sectalign and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
```

**Comment by PetteriAimonen** [comment]
Seems like an issue in CocoaPods build rules for nanopb. I do not know who maintains it.

**Comment by nebiros** [comment]
> Seems like an issue in CocoaPods build rules for nanopb. I do not know who maintains it.

Looks like is a dependency from Firebase

**Comment by nebiros** [comment]
https://github.com/firebase/firebase-ios-sdk/issues/4855
