### ISSUE TITLE
Generate *_pb2.py files in custom folder

### ISSUE THREAD

**Issue by lorenzo-arena** [nanopb/nanopb#490]
**What should the feature do?**

The *_pb2.py should be generated in a custom folder, chosen by the user (maybe via a command line argument). This way, instead of simply ignoring it, it could be created in a "build" folder and removed by a `make clean` on the full project which uses NanoPB.

**In what situation would the feature be useful?**

To be sure that `make clean` cleans everything and to get all generated files in the same folder.

**Comment by PetteriAimonen** [comment]
Version 0.4.7 now reads environment variable `NANOPB_PB2_TEMP_DIR`. This can be set to a temp folder path, or to `1` to use system-wide temp folder. It is not yet enabled by default, but I might consider that in 0.5.0.
