### ISSUE TITLE
Define attribute packed on enums

### ISSUE THREAD

**Issue by twam** [nanopb/nanopb#495]
Is there a way to define `packed_struct` on enums? I tried, but it seems to be ignored.

Would appreciate to be able to set that instead of using a global `-fshort-enums' or similar options on the project.

**Comment by PetteriAimonen** [comment]
There is `packed_enum` option: https://github.com/nanopb/nanopb/blob/master/generator/proto/nanopb.proto#L75

**Comment by twam** [comment]
Awesome! Maybe we should update the 'Proto file options' section on https://jpa.kapsi.fi/nanopb/docs/reference.html :)
