### ISSUE TITLE
Encoding callbacks arg always 4

### ISSUE THREAD

**Issue by rliegmann** [nanopb/nanopb#513]
Hello, I have the following problem:
This is my Encoding callbacks function:
```
bool test_callback(pb_ostream_t *stream, const pb_field_t *field, void * const *arg)
{
    Serial.println("Callback2");
    Serial.println( sizeof(arg));
    return true;
}
```

And the declaration looks like this:
```
sensor.samples.funcs.encode = &test_callback;
sensor.samples.arg = list2;
```

There are 6 entries in list2
The problem is that sizeof(arg) always contains 4 entries. No matter what comes over sensor.samples.arg 

What is my Problem?

thank you in advance

**Comment by PetteriAimonen** [comment]
`sizeof(arg)` in that context will return just the size of a pointer, which is always 4 bytes on your platform. This is normal in C language as `sizeof()` is evaluated at compile time.

You will need to pass the list length separately, for example by putting it in a struct and giving pointer to that, or putting the length as first entry in array.
