### ISSUE TITLE
Default values of +-Infinity and NaN not supported

### ISSUE THREAD

**Issue by jrullman** [nanopb/nanopb#530]
A floating-point field marked with [default = inf] will result in generated code with default value 'inf', which doesn't compile. According to https://developers.google.com/protocol-buffers/docs/reference/proto2-spec#floating-point-literals, 'inf' and 'nan' are allowed values. The generator script should perform the following replacements on default values for floating point fields:

inf -> INFINITY
-inf -> -INFINITY
nan -> NAN
-nan -> -NAN

INFINITY and NAN are defined in math.h.

**Comment by jrullman** [comment]
(INFINITY has to be cast to float in the single-precision case)

**Comment by PetteriAimonen** [comment]
Sounds reasonable.

Currently `math.h` isn't being included, so the include should be added by the generator only if these default values are found in the file.
