### ISSUE TITLE
Message_fields[n].data_offset is unsigned, but offset can be negative

### ISSUE THREAD

**Issue by cm6n** [nanopb/nanopb#541]
**Steps to reproduce the issue**

1. Create a message where data_offset is negative. (See below)
2. Try to pb_encode that message with 64bit pointers (e.g. in a unit test)

Encountered this with nanopb-0.3.9.1. I can try to repro with latest.

**What happens?**
Crash during encoding due to attempt to access an invalid address.

**What should happen?**
Not crash.

__________________________
I suspect the negative offset is a result of the .proto not sorting by tag. The SensorReading struct generated by nanopb matches the order of the .proto. The SensorReading_fields is sorted by tag and pb_encode follows this order. As a result the offset in _fields needs to be negative, but data_offset is unsigned.

.proto
```
message SensorReading {
        int64 sample_timestamp = 38;
        float sample_a = 1;
        float sample_b = 2;
        ... (many more fields)
}
```

In the generated SensorReading_fields, the sample_timestamp entry with tag 38 has data_offset=4294967148. 

When iterating through fields, we the following wraps around nicely and does the right thing if pointers are 32 bits but not if pointers are 64 bits.
```
iter->pData = (char*)iter->pData + prev_size + iter->pos->data_offset;
```

______________

My use case is unit tests for software that ultimately targets a 32-bit device. So for me, switching the unit test build to be 32-bit is a quick fix and probably a good thing in general. In general though:

- is this _supposed_ to work for 64 bit builds?
- is data_offset expected to be negative - if so, maybe a signed type would be better?

**Comment by PetteriAimonen** [comment]
Yes, nanopb is automatically tested with architectures ranging from 8-bit to 64-bit, so it should work.

In nanopb before 0.4.x, the fields in the struct should be in the same order as the generated `_fields` array. Thus data_offset should be always positive. In 0.4.0 and newer absolute offsets are used so the field order is no longer critical, though it remains the same by default for optimal encoding / decoding speed.

When I run the 0.3.9.1 generator on your example, I get this struct:
<pre>
typedef struct _SensorReading {
    float sample_a;
    float sample_b;
    int64_t sample_timestamp;
/* @@protoc_insertion_point(struct:SensorReading) */
} SensorReading;
</pre>
and the `_fields` in `.pb.c` is in matching order.

Are you sure you are running an unmodified 0.3.9.1 version? Have you regenerated both `.pb.h` and `.pb.c` files to make sure they haven't been manually modified?

**Comment by cm6n** [comment]
Thanks for the prompt response! 
After more digging it appears you are right. There's an extra step in this build I was unaware of that reorders the fields in this struct. Looks like this strange behavior is due to our own meddling.

Not a nanopb issue.
