### ISSUE TITLE
Cmake generation not working with grpc-tools

### ISSUE THREAD

**Issue by alexpacini** [nanopb/nanopb#560]
I am trying to setup nanopb using cmake, but it fails in the generation phase requiring protoc.
```bash
CMake Error at /home/alex/.cmake-3.16.5-Linux-x86_64/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Nanopb (missing: PROTOBUF_PROTOC_EXECUTABLE)
Call Stack (most recent call first):
  /home/alex/.cmake-3.16.5-Linux-x86_64/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  lib/nanopb/extra/FindNanopb.cmake:363 (find_package_handle_standard_args)
  CMakeLists.txt:45 (find_package)
```
I have grpc-tools installed and I checked that the function in proto/_utils.py returns True.

Is the grpc-tools also supported by the cmake FindNanopb?

**Comment by PetteriAimonen** [comment]
Yeah, I think the cmake rules may not have been updated to use grpc-tools. Adding the generator folder to search path could work, as the `protoc` wrapper script is there.
