### ISSUE TITLE
Use of anonymous unions in max encoded message size macros fail when compiling in a c++ system

### ISSUE THREAD

**Issue by sammas123** [nanopb/nanopb#562]
I've noticed that nanopb-0.4.1, when compiling a .proto file that imports a second .proto file, can generate max encoded size macros that use anonymous unions inside the sizeof operator. This compiles fine on c11 but will fail for c++ as it is not supported by the language.

Is it possible to modify this behaviour (or add a switch) so that instead of unions, a MAX macro is used instead?

An example is provided as a zip which results in the following:

/* Maximum encoded size of messages (where known) */
#define OuterMessage_size                        (5 + sizeof(union{char f1[SerialConfig_size]; char f2[SerialConfig_size];}))

[interface.zip](https://github.com/nanopb/nanopb/files/4967148/interface.zip)

**Comment by PetteriAimonen** [comment]
This should be already fixed in 0.4.2 (issues #415, #494). Workarounds are mentioned in those bugs.
