### ISSUE TITLE
Is Byte Stuffing Possible?

### ISSUE THREAD

**Issue by llllVIIII** [nanopb/nanopb#574]
Hello, 

I would like to know if it is possible to add byte stuffing like the HDLC (https://en.wikipedia.org/wiki/High-Level_Data_Link_Control) to the pb_encode_ex function? Or can it be achieved without a modification, with a custom ostream object? I don't want to copy the whole encoded pb into another buffer just to perform byte stuffing on it, if possible.

best regards

**Comment by PetteriAimonen** [comment]
Yeah, you can do it with custom ostream.

Or you if you are encoding to a buffer, you can byte-stuff after 
encoding by starting from end of buffer so you can do it inplace.
