### ISSUE TITLE
iOS 10 no longer supported with version 0.3.9.6

### ISSUE THREAD

**Issue by EIDD8680** [nanopb/nanopb#586]
**Steps to reproduce the issue**

1. Install firebase version 6.31.1 with cocoapods, include nanopb version 0.3.9.6 (pod spec 1.30906.0).
2. In Xcode, archived with iOS Deployment Target iOS 10.0. 
3.

**What happens?**

**Ignoring file** /Users/xxxxxx/Library/Developer/Xcode/DerivedData/xxxxxx-xxxxx/Build/Intermediates.noindex/ArchiveIntermediates/xxxxxxx/BuildProductsPath/Recette-iphoneos/nanopb/libnanopb.a, building for iOS-armv7 but attempting to link with file built for iOS-arm64
Undefined symbol: _pb_encode_varint
Undefined symbol: _pb_decode_varint
Undefined symbol: _pb_encode_string
Undefined symbol: _pb_encode_submessage
Undefined symbol: _pb_encode_tag_for_field
Undefined symbol: _pb_read
Undefined symbol: _pb_istream_from_buffer
Undefined symbol: _pb_ostream_from_buffer
Undefined symbol: _pb_decode
Undefined symbol: _pb_release
Undefined symbol: _pb_encode

**What should happen?**
nothing (no warning, no ignoring file, no error). Works well with nonapb version 0.3.9.1 (pod spec 0.3.901).

**Comment by PetteriAimonen** [comment]
Hmm, I have no idea about Xcode or cocoapods, you could try reporting it on https://github.com/google/nanopb-podspec
