### ISSUE TITLE
[Question] Are complex encoding of nested repeated submessages supported?

### ISSUE THREAD

**Issue by dnuch** [nanopb/nanopb#588]
For example:

```
syntax = "proto3";

message line {
  string value = 1;
}

message info {
  repeated line lines = 1;
}

message log {
  repeated info infos = 1;
}
```

I can encode message info and line just fine but log has been problematic. My apologies if this has been answered elsewhere but I can't find an example this complex.

Thanks.

**Comment by PetteriAimonen** [comment]
There are many ways to do this: static allocation, callbacks and malloc(). To figure out what is best for your case, I'll need a bit more information:

- Do you know the maximum number of characters per line, lines per info or infos per log in advance?
- What will you do with the lines once they are decoded?

**Comment by PetteriAimonen** [comment]
Oh, or are you just encoding? But in that case the same questions apply: do you know the maximum sizes, and where do the lines come from?

**Comment by dnuch** [comment]
I ended up getting it to work! Sorry for the noise
