### ISSUE TITLE
MobSF reported use of unsecured function

### ISSUE THREAD

**Issue by Lakshaya** [nanopb/nanopb#600]
We have used MobSF client to analyse our app and it has reported the use of following unsecured functions which are used by nanopb

1.) _memcpy/memcpy

**Comment by PetteriAimonen** [comment]
`memcpy` isn't used in 0.4.0 or newer, though not because it is "unsecured" in any way.

In my opinion such a warning is not useful, and e.g. `memcpy_s` is not supported on most platforms.
