### ISSUE TITLE
Is proto3 officially and fully supported by Nanopb?

### ISSUE THREAD

**Issue by MatanRubin** [nanopb/nanopb#602]
Hi,
Thanks for this project, it's awesome!
I tried finding in the docs a statement about the status of proto3 support but couldn't find it.
Is proto3 officially and fully supported by nanopb? If not, what are the current known issues?

Thanks!

**Comment by PetteriAimonen** [comment]
It's supported.

**Comment by madhat1** [comment]
Is it fully supported?
Starting from which nanopb version is it supported?
