### ISSUE TITLE
Linking error with conan package

### ISSUE THREAD

**Issue by a1lu** [nanopb/nanopb#604]
Hi,
I linked against the nanopb conan package and got the following errors:

```
undefined reference to `pb_ostream_from_buffer'
undefined reference to `pb_encode'
undefined reference to `pb_istream_from_buffer'
undefined reference to `pb_decode'
```
I noticed that the conan recipe does not specify the library to link against, so I added
```
    def package_info(self):
        self.cpp_info.libs = ["protobuf-nanopb"]
```
to conanfile.py and linking works again.

**Comment by PetteriAimonen** [comment]
@amatosov-rbx, @Psy-Kai Do you want to take a look?

**Comment by Psy-Kai** [comment]
I strumbled upon this problem myselfe a few days ago but hat no time to create a pull request. Yes the cpp_info.libs is missing.
