### ISSUE TITLE
Download Pages Not Found

### ISSUE THREAD

**Issue by EvanShenkman-Sonos** [nanopb/nanopb#608]
It seems like none of the release assets can be found on the [Download](https://jpa.kapsi.fi/nanopb/download/) page. I've tried clicking the links for multiple versions and they all return this page...

![image](https://user-images.githubusercontent.com/50674956/96355971-40ab6a00-10b6-11eb-82ed-068ba61d8499.png)

**Comment by PetteriAimonen** [comment]
Thanks for the notice, looks like my web host had an upgrade yesterday and some Python modules broke. Should be fixed now.

**Comment by EvanShenkman-Sonos** [comment]
Yup- it's resolved now. Thanks!
