### ISSUE TITLE
Nanopb cannot communicate with google protobuf

### ISSUE THREAD

**Issue by mejtejt** [nanopb/nanopb#627]
I have two sides of application. One side is using google protobuf c++ (version 3.11.2), and the other side nanopb (version 0.4.5).

This is the proto file on C++ side: 
![image](https://user-images.githubusercontent.com/33463717/103000694-d090e880-452b-11eb-8e85-148483a48868.png)

Part of the code which serializes this is as follows:
![image](https://user-images.githubusercontent.com/33463717/103000837-19e13800-452c-11eb-9a3d-57cd382c2abb.png)

Payload is then sent over UART (part in the brackets [0x8 0x1]):
![image](https://user-images.githubusercontent.com/33463717/103000891-33827f80-452c-11eb-8147-dfd4e7cc770e.png)

On the nanopb side, this message is then received. Following are .proto file and serial output:
![image](https://user-images.githubusercontent.com/33463717/103001024-78a6b180-452c-11eb-8b16-cd2148220e06.png)
![image](https://user-images.githubusercontent.com/33463717/103001908-2feff800-452e-11eb-87df-c49bfe7ffd86.png)

`Payload data` shows what has been sent from C++ side and received on the nanopb side. The problem is, if I try to decode this using `pb_decode` function, it fails with "wrong wire type" error message. 

The next step in trying to identify the problem was the following: I will encode MessageRequest on the nanopb side, and print out the bytes to see what is makes out of it. 
![image](https://user-images.githubusercontent.com/33463717/103001476-5eb99e80-452d-11eb-8af9-1fa321646639.png)
![image](https://user-images.githubusercontent.com/33463717/103001067-907e3580-452c-11eb-86c8-f556195f62e5.png)

As you can see, `Payload data =` is the part received from C++ protobuf. And `Request buffer =` is what comes out after calling pb_encode function. Now decoding, on line 65, works. 

The question is: what is `0xa` and `0x2` part of the request buffer? And why does google protobuf not generate this? This is the part that is making `pb_decode` function to fail. How do I make them compatible (either by making google protobuf generating this (I don't know what it is, so I will call it) header, or to instruct nanopb to not use this during encoding/decoding)?

**Comment by PetteriAimonen** [comment]
First of all, are you using different `.proto` files for encoding and decoding? Why? They should match on each side.

It also appears you are encoding `MetricPair` but trying to decode `MessageRequest`. Because these two message types have different and incompatible structures, decoding will fail. In this case `0x0A 0x02` is the submessage prefix.

**Comment by mejtejt** [comment]
Ahhh, I am so sorry for taking your time on this. You are absolutely right, they should be the same. I am not the only one working on this, that is why they are incompatible (at the moment). But, as you said, they should be identical. 

I have been staring at this so long, that I totally missed what I am encoding is different from what I am decoding. Thanks a lot for a quick response.

**Comment by PetteriAimonen** [comment]
No problem, good to hear you got it working!
