### ISSUE TITLE
is nanopb api thread safe?

### ISSUE THREAD

**Issue by zhangshengping** [nanopb/nanopb#632]
i want to use nanopb in a **multi-thread** program.
and i want to know is nanopb is **thread safe**?

**Comment by PetteriAimonen** [comment]
There is no global state, so using nanopb functions on different messages & streams from different threads is safe.

It is also safe to use read-only functions (the encoder part) to encode same message from multiple threads simultaneously.

However, it is not safe to modify same message or output stream from multiple threads at the same time.
