### ISSUE TITLE
Could not build module 'nanopb'

### ISSUE THREAD

**Issue by Bavon101** [nanopb/nanopb#634]
I'm having an issue creating an archive on ios Flutter release, the  app works well on debug mode and `flutter ios build` is also a success but I still face an issue on `nanopb` on archive.
I thought the issue was Firebase core, [and I raised the issue here](https://github.com/FirebaseExtended/flutterfire/issues/4934)
The error has really troubled me, I've looked for numerous [solutions](https://stackoverflow.com/questions/66027940/im-not-able-to-build-ios-app-archive-in-flutter-due-to-nanopb-header-error) with none being a success

**Comment by PetteriAimonen** [comment]
Well, doesn't really fall in scope of this project either. I'm not sure who maintains whatever build system that uses, but I do not maintain it :)
