### ISSUE TITLE
Unable to use in C#

### ISSUE THREAD

**Issue by LiorBanai** [nanopb/nanopb#642]
getting:
"The type or namespace name 'NanopbReflection' could not be found in the global namespace (are you missing an assembly reference?)"

also , is there any reason to use proto2 instead of proto3?

Thanks

**Comment by PetteriAimonen** [comment]
You'll have to build `nanopb.proto` for your C# library, or put your settings in separate `.options` file.

Proto2 and proto3 have bunch of differences, like default values and required fields. Depends on your application what is better.

**Comment by LiorBanai** [comment]
Thanks!
