### ISSUE TITLE
Add support for removing deprecated fields from max_size #defines

### ISSUE THREAD

**Issue by shreyasbharath** [nanopb/nanopb#651]
It'd be great to exclude deprecated fields from the max_size #defines in the `pb.h` files. This will decrease RAM usage when there's no intention to use the deprecated fields anyway.

This could be a compiler option so as to not break existing behaviour?

**Comment by PetteriAimonen** [comment]
Maybe just add `(nanopb).type = FT_IGNORE` on the deprecated fields, if they are not used in C code.

**Comment by shreyasbharath** [comment]
Didn't know that @PetteriAimonen , thanks for the fast response! Should have RTFM 😆

**Comment by shreyasbharath** [comment]
Is it possible to add two properties like so?

```
sint32 blah = 6 [deprecated = true, (nanopb).type = FT_IGNORE];
```

**Comment by PetteriAimonen** [comment]
Sure, should work. You can also put nanopb-specific options in separate `.options` file if preferred.
