### ISSUE TITLE
Default value of oneof

### ISSUE THREAD

**Issue by AABelkhiria** [nanopb/nanopb#661]
Hello,

I am writing this Issue to ask about a how to.
we want to ask is we're able to set a default value for a which oneof
```
/* proto file */
message msg_structure {
  oneof version {
    uint32 v1 = 1;
    uint32 v2 = 2;
  }
}
```

```
/* pb.h file */
typedef struct _msg_structure { 
    pb_size_t which_version;
    union {
        uint32_t v1;
        uint32_t v2;
    } version; 
} msg_structure;

#define msg_structure_init_default               {0, {0}}
#define msg_structure_init_zero                  {0, {0}}

#define msg_structure_v1_tag                     1
#define msg_structure_v2_tag                     2
```

The goal is to set `which_version` in `msg_structure_init_default` to `msg_structure_v2_tag`

**Comment by PetteriAimonen** [comment]
No, currently there is no support for that.

**Comment by AABelkhiria** [comment]
Thanks for your quick reply.

Is this feature planned in NanoPb roadmap or is it something related to protoc ?

**Comment by PetteriAimonen** [comment]
It could possibly be implemented as a nanopb-specific generator option, but I'm not sure if there is enough use for it.

**Comment by PetteriAimonen** [comment]
There are currently no plans to implement this.
