### ISSUE TITLE
Fail to compile test code

### ISSUE THREAD

**Issue by passerbyd** [nanopb/nanopb#694]
I'm trying to run "alltypes_proto3" test case separately:
1. copy alltypes.proto and encode_alltypes.c into examples/simple.
2. modify Makefile, point source and proto files to encode_alltypes.c and alltypes.proto.
3. run make.

Then there are numbers of errors like:
> encode_alltypes.c:17:14: error: no member named 'rep_int32_count' in 'struct _AllTypes'
>     alltypes.rep_int32_count = 5; alltypes.rep_int32[4] = -2001;
>     ~~~~~~~~ ^
> encode_alltypes.c:17:53: error: subscripted value is not an array, pointer, or vector
>     alltypes.rep_int32_count = 5; alltypes.rep_int32[4] = -2001;
>                                   ~~~~~~~~~~~~~~~~~~^~
> encode_alltypes.c:18:14: error: no member named 'rep_int64_count' in 'struct _AllTypes'
>     alltypes.rep_int64_count = 5; alltypes.rep_int64[4] = -2002;
>     ~~~~~~~~ ^
> encode_alltypes.c:18:53: error: subscripted value is not an array, pointer, or vector
>     alltypes.rep_int64_count = 5; alltypes.rep_int64[4] = -2002;
>                                   ~~~~~~~~~~~~~~~~~~^~

and I checked the generated alltypes.pb.h file. All "repeated" and "string" fields are declared as "pb_callback_t", which can not be assigned with those values.
```
    AllTypes alltypes = AllTypes_init_zero;

    alltypes.rep_int32_count = 5; 
    alltypes.rep_int32[4] = -2001;
    alltypes.rep_int64_count = 5;
    alltypes.rep_int64[4] = -2002;
    alltypes.rep_uint32_count = 5;
    alltypes.rep_uint32[4] = 2003;

    // type of rep_int32 /rep_int64 is struct "pb_callback_t" in generated "alltypes.pb.h"
```

Please help me to figure out which step is wrong.

**Comment by PetteriAimonen** [comment]
Did you copy `alltypes.options` also?

**Comment by passerbyd** [comment]
> 
> 
> Did you copy `alltypes.options` also?

Didn't. I will have a try. But does the generated message struct will be different with options file. The problem is caused because the test code wants to assign an int value to "pb_callback_t" object.

**Comment by PetteriAimonen** [comment]
Yeah, that is exactly what the options do: https://jpa.kapsi.fi/nanopb/docs/concepts.html#data-types

**Comment by passerbyd** [comment]
All works fine since adding options file. Thx.
