### ISSUE TITLE
nanopb_out: protoc-gen-nanopb: Plugin failed with status code 1.

### ISSUE THREAD

**Issue by flybrianfly** [nanopb/nanopb#695]
Running nanopb with CMake in the directory '/home/vagrant/work/spaaro/flight_code/build' I get the following error:

`
[ 82%] Generating nanopb/generator/nanopb_generator.py, nanopb/generator/proto/nanopb.proto
[ 83%] Generating nanopb/generator/proto/nanopb_pb2.py
[ 84%] Running C++ protocol buffer compiler using nanopb plugin on ../common/datalog.proto
/home/vagrant/work/spaaro/flight_code/build/nanopb/generator/protoc-gen-nanopb: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--nanopb_out: protoc-gen-nanopb: Plugin failed with status code 1.
`
Interestingly, if I run the CMake make command again, it compiles on the second try:

`
[ 82%] Generating nanopb/generator/proto/nanopb_pb2.py
[ 83%] Running C++ protocol buffer compiler using nanopb plugin on ../common/datalog.proto
`

I started poking around in the code and found that FindNanopb.cmake copies the nanopb generator to the build directory, so the directory looks correct. Not really sure where to investigate from here. I'd really like to get it to compile on the first try.

**Comment by PetteriAimonen** [comment]
Could be related to #596.

It sounds like there might be some dependency issue in the FindNanopb.cmake.
Are you using parallel builds in CMake?

@leabut or @twam any ideas?
