### ISSUE TITLE
Wrong cast for 'stream.callback' with PB_BUFFER_ONLY

### ISSUE THREAD

**Issue by JuergenHaug** [nanopb/nanopb#717]
Compiling with g++ produces the following error:
```
...\nanopb\pb_encode.c:68:21: error: invalid conversion from 'void*' to 'int*' [-fpermissive]
     stream.callback = (void*)1; /* Just a marker value */
```
I guess the line https://github.com/nanopb/nanopb/blob/ab19ecbe1b9f377ab4ee8e762bfe16c39068ad68/pb_encode.c#L68 has to be
```c
stream.callback = (int*)1; /* Just a marker value */
```

**Comment by PetteriAimonen** [comment]
Thanks.
I chose to make it an actual valid pointer value, just in case some compiler somewhere does not like fake pointers.
