### ISSUE TITLE
FEATURE: use #define to specify array limits

### ISSUE THREAD

**Issue by Xeenych** [nanopb/nanopb#737]
Currently, when I use max_count option e.g. `max_count:6`, nano_pb  hardcodes array size to '6'.
When I want to iterate over array in a for cycle I have to hardcode `6` in multiple places.

Please make a #define of some sort "#define some_message_some_member_max_count 6"

**Comment by PetteriAimonen** [comment]
There exists `pb_arraysize(MyMessage, myfield)` which uses the C standard `sizeof()` to get the size.

**Comment by Xeenych** [comment]
Thanx
