### ISSUE TITLE
FindNanopb.cmake gives misleading error when protoc is not installed

### ISSUE THREAD

**Issue by Jason-Bens-Teufel** [nanopb/nanopb#752]
It looks like HAS_COLON_IN_PATH is asserted when FindNanopb.cmake is executed without protoc installed.  I'm not sure why an empty value in PROTOC_VERSION_STRING is matching to the pattern ":", but the result is that the "Your path includes a ':' character [...]" error is output, which can be confusing (ask me how).  A more helpful message would first check if PROTOC_VERSION_STRING is empty, and warn that protoc isn't found.

Found in nanopb v0.45, on windows.  cmake v3.22.2

**Comment by PetteriAimonen** [comment]
Might even remove that check altogether, considering protoc 3.6 is ancient nowadays.
