### ISSUE TITLE
Allow enum values to not include package information. 

### ISSUE THREAD

**Issue by ankit-agarwal1999** [nanopb/nanopb#753]
Hello, I don't know if this is intended behavior with the `long_names` field, but when I run with `long_names` off, the enum values still include the package information. I was hoping to get a feature where the enum values could not include the package name. 

Right now the current behavior is: 
Protobuf 

```proto3

package my_package

enum my_enum {
    MY_ENUM_ZERO = 0,
    MY_ENUM_ONE = 1,
}
```

Generated file (with long names off): 

```c

typedef enum _my_package_my_enum {
    my_package_MY_ENUM_ZERO,
    my_package_MY_ENUM_ONE,
}my_package_my_enum ;

#define my_package_my_enum_MIN my_package_MY_ENUM_ZERO

```

Generated file (with long names on): 

```c

typedef enum _my_package_my_enum {
    my_package_my_enum_MY_ENUM_ZERO,
    my_package_my_enum_MY_ENUM_ONE,
}my_package_my_enum ;

#define my_package_my_enum_MIN my_package_my_enum_MY_ENUM_ZERO

```

Desired File: 

```c

typedef enum _my_package_my_enum {
    my_enum_MY_ENUM_ZERO,
    my_enum_MY_ENUM_ONE,
}my_enum ;

#define my_package_my_enum_MIN my_enum_MY_ENUM_ZERO

```

I have a workaround already (its a one-line change to the generator) that allows me to do this, but I was wondering if this could be a bug, or potentially a feature request.

**Comment by PetteriAimonen** [comment]
I think the option you want is `(nanopb).mangle_names = M_STRIP_PACKAGE` or even `M_FLATTEN`.
