### ISSUE TITLE
Encoded size define is not generated when type:FT_CALLBACK, even though all information is available

### ISSUE THREAD

**Issue by Krensi** [nanopb/nanopb#755]
It would be very handy if nanopb creates the define with the encoded size, event though the callback type is used. I want to use the callback to store the decoded data right into my own data structure. However, I would also like to pre-allocate the buffer for the encoded string.

See the files below. Even though the .option file provides all information, the define is not created.
[test.zip](https://github.com/nanopb/nanopb/files/8110664/test.zip)

**Comment by PetteriAimonen** [comment]
The reasoning is that the callback does not necessarily obey the limits set in the options.
