### ISSUE TITLE
Question about input stream documentation

### ISSUE THREAD

**Issue by zrno** [nanopb/nanopb#760]
The documentation shows this example for the callback that would read from stdin.
![image](https://user-images.githubusercontent.com/13214299/156500947-e1d98405-2485-4796-ba3e-154bfacb8b61.png)
Why is the red marked part needed? In what case would the buffer be NULL? And also if it can be NULL, why does the example code try to read `count` number of bytes?

**Comment by PetteriAimonen** [comment]
This is used to skip the contents unknown fields.
