### ISSUE TITLE
CppUTest comparator for nanopb structs

### ISSUE THREAD

**Issue by kesyog** [nanopb/nanopb#765]
**What should the feature do?**

The [CppUTest unit test and mocking framework](https://cpputest.github.io/mocking_manual.html) has the concept of "comparators". [Comparators](https://cpputest.github.io/mocking_manual.html#objects_as_parameters) are used to compare two different C/C++ objects.

I have a small patch for a CppUTest comparator that compares two different nanopb C structs by serializing them and comparing their binary serialized output.

**In what situation would the feature be useful?**

The patch would be useful to any users who use the CppUTest unit testing framework and want to test code that serializes or deserializes protobufs using nanopb.

**Questions**

Is this there any interest in adding this to the nanopb repo? If so, where would be a good spot for it?

**Comment by PetteriAimonen** [comment]
I think this is probably too specific to be included in the main nanopb repository. You could post it in this issue report as a comment though, so that if someone happens to need it later, they'll have a starting point.

**Comment by kesyog** [comment]
Sounds reasonable. I'll post it here once I get the requisite approvals from my employer.

**Comment by kesyog** [comment]
Link to repo: https://github.com/google/nanopb-cpputest-comparators
