### ISSUE TITLE
Protoc in generator/ is not found

### ISSUE THREAD

**Issue by a1lu** [nanopb/nanopb#769]
``Hi
https://github.com/nanopb/nanopb/blob/e69913ea42b18141fcd4006c8cd1777a4a2a34f2/CMakeLists.txt#L17-L20

This check fails on my side without a global installation of protoc.

A possible fix is to add a hint to look in `generator` (works on my side):

```
find_program(nanopb_PROTOC_PATH protoc
               HINTS 
               generator
) 
 ```

It is also possible to add `REQUIRED` to avoid the check.

**Comment by PetteriAimonen** [comment]
Yeah, could make sense. Not sure what it should default to though, the global protoc or the `generator/protoc` wrapper script.

**Comment by a1lu** [comment]
My issue was, that the protoc of my distribution was not recent enough to support some flags I needed (see https://github.com/nanopb/nanopb/issues/768). So in my case it would be a good idea to default to the bundled version of protoc to be sure to support everything mentioned in the nanopb docs.

**Comment by PetteriAimonen** [comment]
Added the HINTS now.
