### ISSUE TITLE
FILE DOES NOT COMPILE

### ISSUE THREAD

**Issue by PeterRaafat9504** [nanopb/nanopb#774]
every time i run python generator/nanopb_generator.py myprotocol.proto  # For source checkout or
generator-bin/nanopb_generator myprotocol.proto        # For binary package
i get: could not make proto path relative no such file or directory

**Comment by PetteriAimonen** [comment]
Does the `myprotocol.proto` exist in current execution directory?

In any case, that's not enough information for me to reproduce the problem, you'll have to debug it further yourself.
