### ISSUE TITLE
Download server returns 500 Internal Server Error

### ISSUE THREAD

**Issue by FuchsPhi** [nanopb/nanopb#780]
**Steps to reproduce the issue**
1. Open following URL with your web browser: https://jpa.kapsi.fi/nanopb/download/nanopb-0.4.5-linux-x86.tar.gz

**What happens?**
Get Error: 500 Internal Server Error

**What should happen?**
Latest release should be downloaded.

**Comment by PetteriAimonen** [comment]
Thanks for notifying, this should be fixed now.

**Comment by tom-bresson-bose** [comment]
Hey @PetteriAimonen, this seems to be an issue as of today. Thanks in advance!

**Comment by PetteriAimonen** [comment]
@tom-bresson-bose Thanks - fixed, again. My webhost has been doing some upgrades.
