### ISSUE TITLE
PB_BIND data offset static assertion failing in Segger Embedded Studio (clang and gcc)

### ISSUE THREAD

**Issue by Jason-Bens-Teufel** [nanopb/nanopb#794]
I've got a project that uses nanopb protos to communicate via UART to another device.  It looks like every proto I've defined that's not just an empty message throws a compiler error.  The error is `static_assert expression is not an integral constant expression`.   The compiler also emits a message at that line, saying `cast that performs the conversions of a reinterpret_cast is not allowed in a constant expression`.  I'm aware of the definition that disables static assertions, but would like to keep them enabled if possible.

Digging into the precompiler output, it seems that the error is being thrown in the data offset check, which expands to the following:
```
_Static_assert(((uint32_t) (((size_t) & (((SetVolume *) 0)->volume))) < ((uint32_t) 1 << 8)), "FIELDINFO_DOES_NOT_FIT_width1_field1");
```
The proto itself is pretty simple: 
```
message SetVolume
{
	uint32 volume = 1;
};
```
I've tested this with both clang 13.0.1 and gcc 10.3.1 as supplied by Segger Embedded Studio, and this static assertion threw an error for both.  Both compilers support C17.  I've also used this same code in another related project in vscode, compiled with the Arm GNU embedded toolchain (arm-none-eabi version 9 2019 q4 major), and there were no issues.

**Comment by PetteriAimonen** [comment]
It might also matter where offsetof() macro definition comes from. That 
looks a bit like C-style offsetof used in C++ mode.

**Comment by Jason-Bens-Teufel** [comment]
This is a c++ project, but the project is configured to build .c files with the c compiler.  I've confirmed that the c compiler is being used by placing a check at the top of the .pb.c file to emit a warning if __cplusplus is set.  The full build string, stripping out a million includes, is 
```
"C:\Program Files\SEGGER\SEGGER Embedded Studio for ARM 6.20a\llvm\bin\clang"
-cc1
-disable-free
-disable-llvm-verifier
-fgnuc-version=4.2.1
-mrelocation-model static
-mconstructor-aliases
-x c
-fcolor-diagnostics
-fansi-escape-codes
-std=c17
-triple thumbv7em-none-eabi
-target-cpu cortex-m4
-target-feature
-strict-align
-target-abi aapcs
-mfloat-abi hard
-fno-signed-char
-fallow-half-arguments-and-returns
-mllvm
-arm-global-merge=false
-nostdsysteminc
-nobuiltininc
-D__SIZEOF_WCHAR_T=4
-D__ARM_ARCH_7EM__
-D__SES_ARM
-D__ARM_ARCH_FPV4_SP_D16__
-D__HEAP_SIZE__=1024
-D__SES_VERSION=62001
-D__SEGGER_LINKER
-D_LIBCPP_HAS_NO_THREADS
-D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS
-D__NO_AEABI_ERR__
-D__FPU_PRESENT
-D__FPU_USED
-DARM_MATH_CM4
-DSTM32F407xx
-D__STM32F4xx_FAMILY
-D__STM32F407_SUBFAMILY
-DFLASH_PLACEMENT=1
-DUSE_FULL_LL_DRIVER
-DHSE_VALUE=8000000
-dependency-file C:/proj/Output/PROJ_STM32F407_Debug/Obj/proj/casterlink.d
-sys-header-deps
-MT Output/PROJ_STM32F407_Debug/Obj/proj/casterlink.pb.o
-Wall
-Wextra
-Wstrict-prototypes
-Wstrict-aliasing
-dwarf-version=4
-debug-info-kind=standalone
-debugger-tuning=gdb
-mllvm
-generate-arange-section
-exception-model=dwarf
-gpubnames
-fno-dwarf-directory-asm
-fno-builtin
-fmath-errno
-ffunction-sections
-fdata-sections
-fshort-enums
-fno-common C:\proj\middleware\Modules\casterlink\src\casterlink.pb.c
-E
-o C:/proj/Output/PROJ_STM32F407_Debug/Obj/proj/casterlink.pb_PP.c
```

As near as I can tell, offsetof() is coming from Segger's stddef.h, where it's defined as
```
#define offsetof(s,m) ((size_t)&(((s *)0)->m))
```
I've never had to use this macro before, but wikipedia's got a page on it, as well as a couple alternative definitions.  Curiously, redefining offsetof() to their third alternative definition, 
```
#define offsetof(st, m)  __builtin_offsetof(st, m)
```
 works fine for me.  So, I'm suspecting that Segger is just being pedantic.  What else can I test, here?

**Comment by PetteriAimonen** [comment]
Does defining `PB_C99_STATIC_ASSERT` make any difference?

It looks like gcc and clang special-case `offsetof()` in their headers to avoid spurious errors. But for some reason Segger ships a version of `stddef.h` that is not based on the one by the compiler authors.

For some reason, I still don't get the error message about "constant expression" unless building in C++ mode, but that could also have something to do with what is defined in the headers.

**Comment by Jason-Bens-Teufel** [comment]
Unfortunately, defining `PB_C99_STATIC_ASSERT` doesn't seem to change anything.

I went back to my other project (gcc) and replaced the offsetof definition with Segger's.  As expected, gcc throws a warning:
```
warning: variably modified 'pb_static_assertion_FIELDINFO_DOES_NOT_FIT_width1_field1_13_2' at file scope
```
It's starting to look like this is a Segger problem, not anything in nanopb.  Segger's definition of offsetof just doesn't play nicely with their shipped compilers.  I even tried to use their own compilers, Segger and Segger-NG (whatever that means), and it still throws an error.  I propose to close this issue and I'll bring it up on Segger's support forum, unless there's anything else you'd be interested to try, first.

**Comment by PetteriAimonen** [comment]
Yeah, that warning looks more like the ones I got when trying to reproduce the problem.

I don't currently have any other suggestions.

**Comment by Jason-Bens-Teufel** [comment]
Sounds good.  Closing.

See also: https://forum.segger.com/index.php/Thread/6501-SOLVED-SES-4-20a-g-compiler-error-from-offsetof/ .  Looks like we're not the first people to have run into this.
