### ISSUE TITLE
Add option to serialize using max size always

### ISSUE THREAD

**Issue by adritium** [nanopb/nanopb#797]
The current API requires `ostream.bytes_written` to be passed in `pb_istream_from_buffer`
This requires `ostream.bytes_written` to be passed along with the buffer.

My problem is that my existing framework only allows me to pass a buffer around.
My current workaround is to `pb_encode` twice with the second encode message being to a constant size message

```
message ActualData
{
int a;
bytes field;
message Foo bar;
}

message Wrapper
{
fixed32 size;
bytes payload [(nanopb).max_size = 1024, (nanopb).fixed_length = true];
}
```

This allows me to `pb_decode` _Wrapper_ using its generated `*_max_size` and then I call
`pb_decode` again using `Wrapper.size` and `Wrapper.payload` to decode `message ActualData`

It works but it would be nice to have an option to `pb_encode` without any optimizations so that I can call
`pb_decode` using `ActualData_max_size`.

Or any option in the `.proto` file to specify **use max length encoding**

On my platform, I do not have dynamic memory so my buffers have to be as big as `ActualData_max_size` anyway.

Since I cannot take advantage of the efficient encoding, it's time wasted.

**Comment by PetteriAimonen** [comment]
I've seen the multitude of your questions on StackOverflow, but there are just too many for me to answer.

With nanopb, you can use e.g. `pb_encode_nullterminated()` and `pb_decode_nullterminated()` and then you do not need to care about what is in the rest of the buffer. However for good compatibility with other protobuf implementations, it makes more sense to pass the message length wherever you are transporting the data.

It is possible to pad protobuf messages to a constant length quite simply by encoding an unknown field (see protobuf encoding spec), but it is a niche enough usecase that I won't be including it in main nanopb code.
