### ISSUE TITLE
Generate equality comparison function

### ISSUE THREAD

**Issue by adritium** [nanopb/nanopb#798]
Using `memcmp` does not work because the padding bytes will not necessarily be equal; I spent an hour until I figured this out.

It would be really nice to simply auto-generate a function that compares two structs of same type.

Ideally, it would tell you which field is different

`void compare_my_msg(my_msg_t * m1, my_msg_t * m2, my_msg_fields_eq_t * msg_fields_eq)`

but I would totally settle for a simple `bool is_equal(my_msg_t * m1, my_msg_t * m2)`

**Comment by PetteriAimonen** [comment]
I'm not currently planning to do this in nanopb core, though the functions in `pb_common.h` can be used to implement something similar in user code.
