### ISSUE TITLE
[Bazel] cc_nanopb_proto_library() --library-include-format incorrect when providing additional options.

### ISSUE THREAD

**Issue by randyzhg** [nanopb/nanopb#810]
When passing options to `cc_nanopb_proto_library` (e.g. via `extra_protoc_args`), the library include format option below is interpreted incorrectly. The single quotes are taken as part of the format template.

https://github.com/nanopb/nanopb/blob/404b2f072d46d53c12b87818b86b34ebb6ad1184/BUILD.bazel#L52

When compiling the generated C files this error message is thrown:
```
error: expected identifier or '(' before '\x622e6822'
    6 | '#include"pb.h"'
      | ^~~~~~~~~~~~~~~~
```

This bug does not surface if there aren't additional options needs. There is a work around for this right now and that's to override the format when supplying additional args. e.g.
```python
    extra_protoc_args = [
        "--nanopb_plugin_opt=...,
        "--nanopb_plugin_opt=-L#include\"%s\"",  # Override --library-include-format with this.
    ],
```

**Comment by PetteriAimonen** [comment]
Fixed now for the common case by allowing to specify the include format without using special characters.
Bazel is not the only build system that has had trouble passing the `#` and `""`.
