### ISSUE TITLE
Mark fields as optional

### ISSUE THREAD

**Issue by cristeab** [nanopb/nanopb#813]
Hi
In proto buffer v3.15.0 fields can be marked as optional. Can this feature be used also in nanopb ?
thank you
Bogdan

**Comment by PetteriAimonen** [comment]
Yes, since nanopb-0.4.4. See https://github.com/nanopb/nanopb/tree/master/tests/proto3_optional

Depending on protoc version it may need --experimental_allow_proto3_optional. The nanopb side should work automatically without any special settings.
