### ISSUE TITLE
Q: which C (not c++) grpc library do you use with nanopb?

### ISSUE THREAD

**Issue by mw66** [nanopb/nanopb#823]
Hi,

Maybe a silly question: but which C (not C++) grpc library do you use with nanopb?

(I searched a bit, but didn't find any good / active maintained C (not C++) grpc library on the web).

Or may I use a Rust (or some other language's) grpc library with nanopb? has anyone tried that? any tutorials?

Thanks.

**Comment by PetteriAimonen** [comment]
AFAIK there are no maintained grpc libraries for use with nanopb. There used to be https://github.com/d21d3q/nanogrpc but it is no longer maintained.
