### ISSUE TITLE
python generator works wrong with proto3 optional fields 

### ISSUE THREAD

**Issue by zcteo** [nanopb/nanopb#825]
protoc version 3.21.7
nanopb version 0.4.6.4 python generator

my proto3 file has optional fields
when I compile them use nanopb python generator，I get error as  follow

code generator protoc-gen-nanopb hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--nanopb_out

binary generator works correctly

**Comment by PetteriAimonen** [comment]
That probably means that your `python-protobuf` version is too old. Check the output of this command:

    python -c 'import google.protobuf; print(google.protobuf.__version__)'
