### ISSUE TITLE
running with -q still outputs to stderr if unmatched fields in the options file

### ISSUE THREAD

**Issue by CrustyAuklet** [nanopb/nanopb#831]
The line [here](https://github.com/nanopb/nanopb/blob/master/generator/nanopb_generator.py#L2380), when there are items in the options files that don't match, will print to stderr even in quiet mode.

Seems like a trivial fix, on my machine I indented that if statement once so that it is inside the `elif not options.quiet:` branch. But I am not sure that is the intended semantics.

This is actually causing major issues because at least for my project Ninja is crashing if a command it runs prints to stderr! (I can't explain that, but have shown it though trial and error).

**Comment by PetteriAimonen** [comment]
Thanks, it indeed makes sense for `--quiet` to silence this message also.

It looks like indentation went wrong in commit aecf7a20ce, introduced in nanopb-0.4.0.
