### ISSUE TITLE
Why do I use pb_ ostream_ from_ Buffer (pb_byte_t * buf, size_t buffsize) and buffsize>4 with fast cycle time will cause code crash?

### ISSUE THREAD

**Issue by niubbbbbbbb** [nanopb/nanopb#842]
Please tell me it's urgent

**Comment by niubbbbbbbb** [comment]
cycle time < 100ms

**Comment by PetteriAimonen** [comment]
There is no way for anyone else to know. You need to debug your program yourself, it is just C code and you have all the source code available.
