### ISSUE TITLE
Include comments from the .proto file in the generated .pb.h file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nanopb/nanopb#85]
```
Protocol Buffers 2.5.0 protoc allows including the comments in the output data 
by specifying --include_source_info. This could be used to include the comments 
also in files generated by nanopb.
```

Original issue reported on code.google.com by `Petteri.Aimonen` on 11 Sep 2013 at 11:37

**Comment by NickeZ** [comment]
This would have been very nice so that auto-generated docs (.e.g with doxygen) pick up these comments.

**Comment by AngelVI13** [comment]
Are there any plans for this feature? I would be willing to work on this. Do you have any guide for contributors?

**Comment by PetteriAimonen** [comment]
@AngelVI13 It would be great if you can work on it! I haven't really looked into it in detail, but here is the basic idea:

1. Figure out how protoc puts the comment info in the data. This is easiest to figure out using the two-step process for calling generator, i.e. `protoc -ofoo.pb foo.proto` `nanopb_generator.py foo.pb`. Then you can decode the `foo.pb` with something like `protoc --decode=google.protobuf.compiler.CodeGeneratorRequest plugin.proto < foo.pb` to see what it contains.

2. Parse the comments in the generator, this is probably best done inside the `ProtoFile` class.

3. Somehow emit the relevant comments before each message and each field of them in `generate_header()`.

**Comment by AngelVI13** [comment]
I have made some progress on the topic. Currently I got leading and trailing comments for enum members to work on my local branch. I would like to get your feedback before proceeding. Any chance you can allow me to push my branch and create a PR ?

**Comment by PetteriAimonen** [comment]
@AngelVI13 You can fork the repository on GitHub and push there to make a pull request, no permissions needed. https://guides.github.com/activities/forking/
