### ISSUE TITLE
Insecure API when using in React Native iOS app

### ISSUE THREAD

**Issue by master4-2021** [nanopb/nanopb#852]
There are some insecure APIs that exists in this repository that Apple considered insecure and recommended not using:
https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/BufferOverflows.html#//apple_ref/doc/uid/TP40002577-SW1

These are reported when using Mobile Security Framework (https://github.com/MobSF/Mobile-Security-Framework-MobSF) to scan the IPA.

memcry: 
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/tests/without_64bit/encode_alltypes.c#L29
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/tests/without_64bit/encode_alltypes.c#L33
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/tests/alltypes/encode_alltypes.c#L41
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/tests/alltypes/encode_alltypes.c#L45
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/tests/alltypes_proto3/encode_alltypes.c#L36
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/tests/alltypes_proto3/encode_alltypes.c#L47
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/tests/field_size_16_proto3/encode_alltypes.c#L36
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/tests/field_size_16_proto3/encode_alltypes.c#L47
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/tests/backwards_compatibility/encode_legacy.c#L39
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/tests/backwards_compatibility/encode_legacy.c#L62
https://github.com/nanopb/nanopb/blob/29d3f03bcff342bac24babf718b832416695b802/tests/fuzztest/random_data.c#L164
https://github.com/nanopb/nanopb/blob/29d3f03bcff342bac24babf718b832416695b802/tests/fuzztest/random_data.c#L186
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/tests/raw_decode/raw_decode.c#L25
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/tests/raw_decode/raw_decode.c#L29
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/tests/fuzztest/flakystream.c#L18
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/tests/regression/issue_504/test.c#L28
https://github.com/nanopb/nanopb/blob/29b8ee492ec33dbd6f2f25203705803cb70b28e4/extra/pb_syshdr.h#L90

I understand that the use of these function does not definitely leads to security issues, but I want to bring this to your attention, and check if these are safe to use within our application.

**Comment by PetteriAimonen** [comment]
I don't really understand - all of the instances you list are in test suite, not in actual library code?

But besides that, as long as we are going to be using C, it is not possible to fully avoid functions that are equivalent to `memcpy()`.
