### ISSUE TITLE
How can we get field names and message names of the protobuffer

### ISSUE THREAD

**Issue by Malhaar-k** [nanopb/nanopb#854]
I need the field names and the message name as a string for my esp32 project.
Is there a way to set a default value for a string in the proto file?

**Comment by PetteriAimonen** [comment]
You can set proto2 default values [the normal way](https://protobuf.dev/programming-guides/proto/#optional). Proto3 syntax doesn't allow setting default values.

**Comment by Malhaar-k** [comment]
Is there no way to get message names and field names in the form of strings?

**Comment by Malhaar-k** [comment]
[This](https://stackoverflow.com/questions/75517756/how-do-i-get-field-names-and-the-message-name-using-nanopb-in-c) solution worked for my application.
