### ISSUE TITLE
Difficulty compiling nanopb for ARM/musl libc

### ISSUE THREAD

**Issue by strophy** [nanopb/nanopb#858]
I'm trying to add nanopb to https://github.com/rvolosatovs/docker-protobuf which is used to build the `rvolosatovs/protoc` Docker image, an all-in-one tool to compile protos to any language using `protoc` plugins. A user [requested](https://github.com/rvolosatovs/docker-protobuf/issues/164) us to add nanopb to the tool.

I have successfully built the plugin using `tools/make_linux_package.sh`, but it results in a binary with around 33MB of Python dependencies. I also noticed that it assumes the user's arch is `x86_64`, but we also hope to build for `aarch64` to release a Docker image with multiarch support. My initial naive attempt is [here](https://github.com/rvolosatovs/docker-protobuf/pull/180).

Is the Python runtime required to use nanopb, or is there some other way to build it using C toolchains only? Does anyone have experience compiling nanopb on ARM or (better yet) have existing protoc plugin binaries built against musl libc, so we can release it in our Alpine-based image?

**Comment by PetteriAimonen** [comment]
The nanopb generator is pure python. It can be installed using e.g. `pip install nanopb`, which will make the `protoc-gen-nanopb` script available.

The `make_linux_package.sh` script makes a binary distribution that contains Python and all dependencies, for convenience where system doesn't have Python yet.

The C library part is only needed for the nanopb runtime, it is not used during `.proto` compilation.

**Comment by strophy** [comment]
Thanks for the clear explanation, this works fine for me now.
