### ISSUE TITLE
mangle_names not working on v0.4.7

### ISSUE THREAD

**Issue by tg-cricut** [nanopb/nanopb#865]
There is a bug when file_a.proto includes file_b.proto which has a package definition.  Using mangle_names=M_STRIP_PACKAGE in both .proto files eliminates the enum and package names added to the front of the enum variables but file_a.pb.h still uses the long name in the _init_default initializer.  Since the _MIN version of the long name doesn't exist and isn't handled by the translation from long name to short name, the generated code will fail to compile on GCC.  

**Steps to reproduce the issue**

1. Generate the .c/.h files from the attached file_a.proto and file_b.proto.
2. Compile file_a.pb.h, file_a.pb.c, file_b.pb.h, file_b.ph.c using gcc.

**What happens?**

GCC will fail with an error due to _error_package_GenericErrorType_MIN not being defined.

file_b.pb.h has:
   #define GenericError_init_default                {_error_package_GenericErrorType_MIN, _error_package_GenericErrorSeverity_MIN}

file_a.pb.h has:
   #define _GenericErrorType_MIN GENERIC_ERROR_UNKNOWN

**What should happen?**

The code compiles.  Either file_a.pb.h needs to use the shortened names in the enum initializers (_init_default) or the long names need to be defined in the file_b.pb.h along with the long name translations. 

I changed the file extension so it could be posted here. 
[file_a.pb.h.txt](https://github.com/nanopb/nanopb/files/11223446/file_a.pb.h.txt)
[file_a.proto.txt](https://github.com/nanopb/nanopb/files/11223447/file_a.proto.txt)
[file_b.pb.c.txt](https://github.com/nanopb/nanopb/files/11223448/file_b.pb.c.txt)
[file_b.pb.h.txt](https://github.com/nanopb/nanopb/files/11223449/file_b.pb.h.txt)
[file_b.proto.txt](https://github.com/nanopb/nanopb/files/11223450/file_b.proto.txt)
[file_a.pb.c.txt](https://github.com/nanopb/nanopb/files/11223451/file_a.pb.c.txt)

**Comment by joshstrohminger** [comment]
Of the two expected behaviors, I'm guessing the preferred solution is the second one, to included the long names in file_b.pb.h, mostly because that's kind of already being done in the section that starts with the comment `/* Mapping from canonical names (mangle_names or overridden package name) */`. I got that working in a fork so I'll submit a PR for it.
