### ISSUE TITLE
Generation of PB_STATIC_ASSERT can lead to an identified that exceeds compiler maximum length

### ISSUE THREAD

**Issue by wjohnsaunders** [nanopb/nanopb#869]
The generation of the PB_STATIC_ASSERT by nanopb_generator.py includes a concatenation of the message names in the variable msgs which is appended to YOU_MUST_DEFINE_PB_FIELD_??BIT_FOR_MESSAGES_ (both 16 and 32 bit asserts).

With a lot of fields to check, this can result in a single identifier that exceeds the compilers maximum identifier length. For example Microsoft compilers have a 2047 character limit. In addition the line length becomes extremely long which can be awkward to view in an editor.

A more scalable approach would be to generate a PB_STATIC_ASSERT line for every field that needs checking. This would also have the advantage of allowing you to know which field caused the assert by the line the assert is thrown from.

**Comment by PetteriAimonen** [comment]
This issue seems to affect only nanopb versions prior to 0.4.0. I do not consider the issue important enough for a backported fix, so I'm closing off this issue.
