### ISSUE TITLE
Make iterator capable of walking const structs

### ISSUE THREAD

**Issue by ajeddeloh** [nanopb/nanopb#871]
**What should the feature do?**

the `pb_field_iter_*()` functions should have const equivalents that allow iterating though `const` proto structs, taking a `const void* message`

**In what situation would the feature be useful?**

We use protobufs for our device configuration and store the decoded protobuf in flash. It would be be nice to be able to use `pb_field_iter_{begin,next,find}` to access those structs. For example, the device may respond to a request to get a field from its configuration using `pb_field_iter_find` but that doesn't work because they're stored in flash and thus are const.

**Comment by PetteriAimonen** [comment]
There is already `pb_field_iter_begin_const()`, which internally casts away constness.
It requires care from the calling code not to write to the non-const pointers that point to const objects.

Duplicating all code just to track constness doesn't seem like a good idea.
