### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rossburton** [nanopb/nanopb#902]
Are there plans for a new release?  We use nanopb with cmake and the 0.4.7 release is broken (eg https://github.com/nanopb/nanopb/commit/01ca6298754b43b518390e433ee30162a65dd05b).

**Comment by PetteriAimonen** [comment]
#845 is still unsolved, so cmake is probably broken at least to some extent in the master branch also.

Currently it doesn't seem I have time to fix it in any near future, though I might make a new release to get the other stuff out at least.

**Comment by PetteriAimonen** [comment]
0.4.8 is published now.
