### ISSUE TITLE
Feature Request: Support App Privacy Manifest

### ISSUE THREAD

**Issue by MichaelFoden** [nanopb/nanopb#910]
Apple required App Privacy manifests until Spring 2024 .
If using particular APIs as outlined by Apple, third-party SDKs also require support.
I would like to know when you adopt this change.
If no action is required, please let us know.

●Questions
1. Dose nanopb sdk use those particular APIs?
2. If it’s used, can support be provided for it?

●References
https://developer.apple.com/videos/play/wwdc2023/10060/
https://developer.apple.com/news/?id=av1nevon
https://developer.apple.com/app-store/user-privacy-and-data-use/

Please check it out. Thanks!

**Comment by PetteriAimonen** [comment]
This does not seem relevant to the nanopb core project. If you are using some project that packages nanopb for use on iOS, please contact them instead.

**Comment by MichaelFoden** [comment]
Thank you for quick response.
Does that mean nanopb doesn’t use any of Apple’s APIs?

**Comment by esteluk** [comment]
@PetteriAimonen I don't know if you've seen https://developer.apple.com/support/third-party-SDK-requirements/ yet, which explicitly calls out nanopb (and/or its consumers) as requiring a mandatory manifest.

**Comment by paulb777** [comment]
We're working on privacy manifests for Firebase now and should be able to do one for nanopb (at least 0.3.*), as well, in the next several weeks. https://github.com/firebase/firebase-ios-sdk/issues/11490  cc: @ncooke3

**Comment by nabs-m** [comment]
Can we reopen this issue since there seems to be a plan to add a privacy manifest to nanopb?

**Comment by PetteriAimonen** [comment]
We can reopen it, but I reiterate that I do not have a plan nor time to study what Apple is trying to require. If Paul can or anyone else provides a pull request, I'll of course review and merge it as appropriate.

**Comment by PetteriAimonen** [comment]
This should now be resolved thanks to ncooke3.
