### ISSUE TITLE
Question: Is it safe to assume has_xxx have always default value?

### ISSUE THREAD

**Issue by MaJerle** [nanopb/nanopb#917]
Imagine this message structure:

```
syntax = "proto3";

message inner {
    optional int32 a = 1;
    optional int32 b = 2;
};

message outer {
    //other fields here...
    inner c = 1;
};
```
Generated:
```c
/* Struct definitions */
typedef struct _inner {
    bool has_a;
    int32_t a;
    bool has_b;
    int32_t b;
} inner;

typedef struct _outer {
    /* other fields here... */
    bool has_c;
    inner c;
} outer;
```

Is it safe to assume:

- that structure `outer` will always have `bool has_c` field, even if `outer` doesn't have explicit `optional` field specified?
- that if `c` in the `outer` hasn't been parsed, then `c.has_a == false`?

For the point `2`, essentially question is how I must ensure check statement:

```c
outer msg;

pb_decode(....)

// Option 1
if (msg.c.has_a) {
//do something
}

// Option 2
if (msg.has_c && msg.c.has_a) {
//do something
}
```
Can I safely use option 1, even if `msg.has_c` is false?

**Comment by PetteriAimonen** [comment]
Yes, those are safe assumptions for proto3 syntax with nanopb >= 0.4.0. For 0.3.x the outer has_c [didn't get generated by default](https://jpa.kapsi.fi/nanopb/docs/migration.html#submessages-now-have-has_field-in-proto3-mode).

For single nested fields nanopb will always initialize the submessage even if it is not present. Note that for repeated fields the count gets initialized to zero but the contents of the array are not initialized.
