### ISSUE TITLE
FeatureReq: Macros to read/write primitive optional fields

### ISSUE THREAD

**Issue by MaJerle** [nanopb/nanopb#918]
Following the protothread best practices, it is not recommended to have any required field in the message: https://protobuf.dev/programming-guides/dos-donts/#add-required

There are likely many primitive types in the application, so it may make sense to have a simple macros that would check if field is set and when user sets the value, it also sets the `has_xxx` field.

Some macro examples, most important is indeed to set `has_x` to true automatically.

```c
#define PB_OPTIONAL_HAS_VALUE(struct_ptr, field_name) ((struct_ptr)->has_##field_name)
#define PB_OPTIONAL_SET_VALUE_PRIM(struct_ptr, field_name, val)                                                        \
    do {                                                                                                               \
        (struct_ptr)->has_##field_name = true;                                                                         \
        (struct_ptr)->field_name = (val);                                                                              \
    } while (0)
```

```c
typedef struct {
    bool has_a;
    int32_t a;
}
```

Which could then be used as:
```c
//Set the value and set the has_a true
PB_OPTIONAL_SET_VALUE_PRIM(&msg, a, 5);

if (PB_OPTIONAL_HAS_VALUE(&msg, a)) {
 //...
}
```

Let me know your thoughts.

**Comment by PetteriAimonen** [comment]
Nowadays with proto3 syntax, I think using explicit "optional" is discouraged also.
I also don't entirely agree with the recommendation of avoiding required fields - if the field really is required and you use proto2, make it required. It can always be converted to optional later.

I have considered such macros before, but I think it will just hide actual functionality. User code can define helper macros if it wants.
