### ISSUE TITLE
error when using nanopb but not protoc

### ISSUE THREAD

**Issue by alelec13** [nanopb/nanopb#929]
Hi,
I'm trying to generate a c code using nanopb for a proto file. This proto file is compiling without problems with protoc for any output code but i get this error using nanopb.

[uDoorAPI.txt](https://github.com/nanopb/nanopb/files/13716710/uDoorAPI.txt)

(renamed in .txt to be updatable)

Output:
error: Only scalar value types may be optional.

**Comment by PetteriAimonen** [comment]
Works for me with newest git master. What version are you using?

**Comment by alelec13** [comment]
Sorry wrong tool... I'm trying to get something working for generating C code. I got confused between nanopb and pbtools. I'll try to get nanopb installed
