### ISSUE TITLE
Add encoded size to C++ output

### ISSUE THREAD

**Issue by denravonska** [nanopb/nanopb#932]
We have a message queue where we can push messages of different types to be funneled further by a task. The message handling is a lot of repetition based on the data type

```Cpp
case SendDisconnect:
    PublishMessageFromBuffer<Disconnect, Disconnect_size>(disconnectTopic, Disconnect_fields);
    break;
```

This is both tedious to read and error prone if you specify the wrong size (`Connect_size` vs `Disconnect_size`). 
Right now we're using the C interface and are considering switching to the C++ helpers. If the helpers also included the maximum size those calls could be made easier to read and harder to get wrong:

```Cpp
case SendDisconnect:
    PublishMessageFromBuffer<Disconnect>(disconnectTopic);
    break;
```

**Comment by PetteriAimonen** [comment]
Seems reasonable. I'm not going to work on this myself any time soon, but it would probably be quite straightforward to imitate pull request #931 to add the feature.

**Comment by denravonska** [comment]
I have something that works but isn't ideal. The encoded size for C is done in `ProtoFile.generate_header` where it injects its dependencies into `Message.encoded_size`. The C++ part happens in `Message.fields_declaration_cpp_lookup` which doesn't have access to the ProtoFile dependencies.

As a test I introduced a `Message.max_size` field which is populated during header generation and used in the C++ lookup generation. Far from neat :(

**Comment by PetteriAimonen** [comment]
Could it generate a function or const variable that references the C `#define`?

**Comment by denravonska** [comment]
> Could it generate a function or const variable that references the C `#define`?

That was one of my approaches, but the C define isn't always there and the C++ generator doesn't know :(

**Comment by PetteriAimonen** [comment]
Hmm, `#ifdef` would be one approach. But I'm also open to some refactoring in the generator if needed.

**Comment by denravonska** [comment]
I'll post a PR so you can have a look.
