### ISSUE TITLE
pb_decode returning false and err msg saying "Wrong wire type" 

### ISSUE THREAD

**Issue by mfran89** [nanopb/nanopb#944]
Hi, 
Recently started using the nanopb library for an arm microcontroller to receive Protobuf messages and send them back too, over tcp . 

I am currently running nanopb-0.4.8 and the steps I took to convert my proto file that uses proto3 to c headers by running the python script nanopb_generator.py . That worked and I copied over the files it created (a proto.h proto.c) as well as the classes for pb_common, pb_decode, pb_encode, and pb.h to the arm microcontroller I am building this software on. I was able to build the code succssfully on the MCU. 

The issue is when the code is running and I get the message and pass the serialized message to pb_decode I got a false status and the error saying "Wrong wire type" . This doesnt make sense to me since online it says proto2 and proto3 are compatible with each other. Here are the steps I take before getting to that point. 
 //using nanopb functions on MCU
    proto_msg rqtMsg = proto_msg_init_zero;     
    /* Create a stream that reads from the buffer. */
    pb_istream_t input_stream = pb_istream_from_buffer(p->payload, p->len); //this is the serial message I get from tcp
    bool status = pb_decode(&input_stream, proto_msg_fields, &rqtMsg);

The interesting thing is even though it is false I am able to decode the message properly for the most part and do what I need to. I am just not sure this error is bad or not. Every now and then the app that sends me proto msgs will give me a msg that doesnt look right but I can decode to a msg that will be processed even though it's the wrong one. So I am trying to figure out how to fix this issue. For more context on the application that is sending me the proto messages it's using.c bindings for protobuf and not nanopb headers since it can use those. Any suggestions?

**Comment by PetteriAimonen** [comment]
[Wire type](https://protobuf.dev/programming-guides/encoding/#structure) refers to the protobuf encoding, where each field is preceded by an indentifier that contains the type of data.

Your case sounds like the beginning of the message data is correct, but there is some garbage at the end.

Make sure that the length you pass to `pb_istream_from_buffer()` is the length of the actual message, and not the size of the total buffer.
