### ISSUE TITLE
(nanopb_msgopt).skip_message does not skip generation of map types

### ISSUE THREAD

**Issue by canton7** [nanopb/nanopb#956]
Hi,

I've run across a problem using `skip_message` with messages which contain a map.

```proto
message Test {
    option (nanopb_msgopt).skip_message = true;

    map<uint32, uint32> map = 1;
}
```

nanopb still generates the type `test_map_entry_t_msg` and associated data, tags, etc.

If you do something like this:

```proto
message Test {
    option (nanopb_msgopt).skip_message = true;

    message Value {
        option (nanopb_msgopt).skip_message = true;
        uint32 dummy = 1;
    }

    map<uint32, Value> map = 1;
}
```

Then you get a compiler error, because the generated `test_map_entry_t` refers to `test_value_t`, which isn't defined.

Thanks!

**Comment by PetteriAimonen** [comment]
As a workaround, you can use wildcard in .options file:

    Test.* skip_message:true

Protoc generates the `MapEntry` message automatically, but there doesn't seem to be a way to define options for it.
Nanopb generator should check for messages that have `options.map_entry = true` if any other messages refer to them. If not, skip generation.

**Comment by canton7** [comment]
Fantastic, thank you!
