### ISSUE TITLE
Issue when check source

### ISSUE THREAD

**Issue by Saiiijchan** [nanopb/nanopb#979]
Dear all
I am a newbie to nanopb and encountered a problem when following the readme. After clone the code base, input "python generator/nanopb_generator.py myprotocol.proto" and the erroe message was showed below
`Could not make proto path relative: myprotocol.proto: No such file or directory

**Comment by PetteriAimonen** [comment]
Is there a file `myprotocol.proto`?

**Comment by Saiiijchan** [comment]
There is no such file in nanopb/ . Is there somethong wrong with protobuf?

**Comment by PetteriAimonen** [comment]
You are supposed to replace the name `myprotocol.proto` with the name of the protobuf definition file that you have written and want to compile. There are some under `examples` folder if you want to test.

**Comment by Saiiijchan** [comment]
Thank you for your answer！

**Comment by cristianfunes79** [comment]
Should this issue be closed?
