### ISSUE TITLE
Can't generate code for service-rpc lines, for C

### ISSUE THREAD

**Issue by YehonatanE** [nanopb/nanopb#982]
Hi,

I am trying to generate RPC code for C using nanopb, but I haven't been successful. When generating the code for Python, it worked well.

-     I tried using the latest version of nanopb, but without success.

Here is the code I am working with:

```syntax = "proto2";

import "google/protobuf/descriptor.proto";

message HttpRule{
    optional string get = 1;
}

extend google.protobuf.MethodOptions {
    optional HttpRule http = 72295730;
}

service Messaging {
    rpc GetMessage(GetMessageRequest) returns (Message) {
        option (http) = {
              get: "/v1/{name=messages/ *}"
        };
    }
}
message GetMessageRequest {
    required string name = 1; // Mapped to URL path.
}
message Message {
    required string text = 1; // The resource content.
}
```

Could you please help me with this?
Thanks

**Comment by PetteriAimonen** [comment]
There is no RPC support in nanopb (related: #248, https://github.com/d21d3q/nanogrpc )
