### ISSUE TITLE
Add support for non VLA

### ISSUE THREAD

**Issue by cristianfunes79** [nanopb/nanopb#983]
**What should the feature do?**
Allow to use nanopb on compilers without support for variable length arrays.

**In what situation would the feature be useful?**
When using C90 compiler.

**Comment by PetteriAimonen** [comment]
Hmm, where are VLAs currently used?

**Comment by PetteriAimonen** [comment]
I'm closing off this issue because there has not been any reply. I'm not currently aware of nanopb using VLAs.
