### ISSUE TITLE
Decoding strings of type FT_POINTER

### ISSUE THREAD

**Issue by jaskij** [nanopb/nanopb#985]
I'm trying to find the documentation for decoding strings when the type is set to FT_POINTER, and can not find anything.

The only info I have been able to find is this [Google groups discussion from 2021](https://groups.google.com/g/nanopb/c/1EejzlsipXA).

What is the current behavior?

I'm fine if it remains unsupported, but it would be nice to mention it in the documentation.

**Comment by PetteriAimonen** [comment]
`FT_POINTER` with any field type will allocate memory with `pb_realloc()` on decoding. On encoding you can provide your own pointers.

**Comment by jaskij** [comment]
Thanks for the info. FT_STATIC it is then.
