### ISSUE TITLE
NanoPBOptions.fallback_type and circular dependencies 

### ISSUE THREAD

**Issue by inolen** [nanopb/nanopb#996]
I'm working on a project where nanopb_generator.py is called with `-s fallback_type:FT_POINTER`.

When doing so, I get a warning about a particular circular dependency being broken by converting the field to FT_CALLBACK. However, if I manually specify that field to be FT_POINTER in the .options file I get no such warning.

This feels inconsistent - it seems in both cases this field's type should be FT_POINTER so the behavior should be the same. However, I wanted to double check here that my understanding is correct before digging through this check_recursive_dependencies code.

**Comment by PetteriAimonen** [comment]
Is it a repeated field, i.e. is it using `fallback_type` at all? In quick code review I couldn't figure out where the bug would occur, but I haven't tried reproducing it yet.

**Comment by inolen** [comment]
Ah! I see, I didn't realize repeated fields were the only place it was used.

Would it make sense to apply it - if it's set to FT_POINTER - rather than falling back to FT_CALLBACK when breaking circular dependencies?

**Comment by PetteriAimonen** [comment]
I think it would make sense.
